import { YouthCluster, Language } from "../types";

export const clusters = [
  {
    name: YouthCluster.GrowthMindset,
    language: Language.English,
    label: 'Growth Mindset',
    summaryPageDescription: 'An athlete’s ability to celebrate signs of progress throughout the year, feel empowered to try new things, and embrace challenges.',
    description: 'An athlete’s ability to celebrate signs of progress throughout the year, feel empowered to try new things, and embrace challenges.',
    funFact: 'Athletes who score high on Growth Mindset tend to score low on perceived levels of stress.',
  },
  {
    name: YouthCluster.SelfConfidence,
    language: Language.English,
    label: 'Self-Confidence',
    summaryPageDescription: 'An athlete’s self-awareness and openness to ask for help when needed. This also includes willingness to ask questions, having a healthy way to handle pressure from others, and loving their sport.',
    description: 'An athlete’s self-awareness and openness to ask for help when needed. This also includes willingness to ask questions, having a healthy way to handle pressure from others, and loving their sport.',
    funFact: 'Athletes who report higher levels of self-confidence are also likely to report higher levels of meaning and purpose.',
  },
  {
    name: YouthCluster.TeamCulture,
    language: Language.English,
    label: 'Team Culture',
    summaryPageDescription: 'Feeling valued on a team regardless of performance, playing for a team that focuses on more than wins and losses, and choosing clubs that create supportive and positive environments.',
    description: 'Feeling valued on a team regardless of performance, playing for a team that focuses on more than wins and losses, and choosing clubs that create supportive and positive environments.',
    funFact: 'Athletes who score higher on Team Culture are also likely to report higher levels of life satisfaction.',
  },
  {
    name: YouthCluster.HealthBehaviors,
    language: Language.English,
    label: 'Health Behaviors',
    summaryPageDescription: 'The athlete’s commitment to maintaining mental and physical health. This category includes sleep, managing social media use, and taking rest days.',
    description: 'The athlete’s commitment to maintaining mental and physical health. This category includes sleep, managing social media use, and taking rest days.',
    funFact: 'Athletes who score high in Health Behaviors tend to also have stronger overall mental and physical health.',
  },
]

export const percentileInterpretationYouth = [
  {
    name: YouthCluster.GrowthMindset,
    language: Language.English,
    minPercentile: 0,
    maxPercentile: 20,
    meaning: 'Based on your Growth Mindset score, you are still learning to deal with the pressures of competition, how to embrace challenges, and how to let go of things outside of your control. It can be hard to be consistent with important skills like those. Youth athletes with high scores in this area tend to cope well with the ups and downs in sport. They don’t worry too much about the performance of others or the outcome of competitions. Instead, they focus on what they can control. They work hard in practice and competition to be the best athlete they can be.',
    next_steps: 'To improve your scores in this area, consider journaling regularly about your experiences and asking yourself, "What went well? What’s worth improving?" after each game or practice. Make sure you celebrate signs of progress throughout the season and set goals you can reach for the season with hard work.',
  },
  {
    name: YouthCluster.GrowthMindset,
    language: Language.English,
    minPercentile: 30,
    maxPercentile: 80,
    meaning: 'Your Growth Mindset score is similar to the majority of other youth athletes. This score means you can often deal with pressure, accept challenges, and let go of things outside of your control–but you might not be doing it consistently yet. Youth athletes with scores similar to yours in this area will be okay with the ups and downs in sport. They may sometimes worry about their team’s performance and whether they are winning or losing. At times, they might be afraid to make mistakes or try new things.',
    next_steps: 'To work on this area, focus on what is in your control. Set goals that have nothing to do with winning or losing, and celebrate signs of progress throughout your season. Try to find something good in every game or practice. When faced with challenges or uncomfortable situations, remind yourself that failure is a part of success and will help you in the long run. It can help to start a journal where you write down "What went well?” and “What’s worth improving?" after each game or practice.',
  },
  {
    name: YouthCluster.GrowthMindset,
    language: Language.English,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Your Growth Mindset score is in the above average range in comparison to other youth athletes. This score shows you are learning important skills in sport that will make you a better athlete in the future. These skills include dealing with pressure, accepting challenges, and letting go of things outside of your control. Youth athletes with high scores in this area are also likely to be okay with the ups and downs in sport. They’re not likely to worry about the performance of others or winning/losing. Instead, they focus on what they control and work hard in practice and competition to be the best athlete they can be.',
    next_steps: 'To maintain your scores in this area, consider journaling regularly about your experiences and asking yourself, "What went well? What’s worth improving?" after each game or practice. Make sure you celebrate signs of progress throughout the season and set goals you can reach for the season with hard work.',
  },
  {
    name: YouthCluster.SelfConfidence,
    language: Language.English,
    minPercentile: 0,
    maxPercentile: 20,
    meaning: 'Your Self-Confidence score is lower compared to other youth athletes. Self-confidence is your core beliefs about yourself. Your score suggests that you are still strengthening your views and beliefs about yourself. Those who score higher in this category, use healthy coping skills. You are still in the process of learning them and applying them to your life, and that is okay!',
    next_steps: 'To improve your self-confidence, try to start asking more questions in practice. Let your coach know how you’re doing and how you’re feeling. It’s okay if you don’t feel comfortable right away–try to start with small questions and small pieces of information, and then ask for help more often as you get more comfortable. Another thing you can do to help you think positively and improve your confidence is to write down 3 good things you did at each practice or game. If you don’t know, ask your coach to help! Finally, remember to focus on being the best athlete you can be regardless of what other people think, say, or do.',
  },
  {
    name: YouthCluster.SelfConfidence,
    language: Language.English,
    minPercentile: 30,
    maxPercentile: 80,
    meaning: 'Your Self-Confidence score was similar to other youth athletes. Self-confidence is your beliefs about yourself and your abilities. This score shows that you may at times feel like you are good enough just the way you are, and other times you may feel like you are not good enough. You may know some coping skills and use them at times, but might not use them as often as you could. Athletes with scores like yours can ask questions and ask for help when needed, but may not do it as often as they could. They can deal with pressure most of the time, but may struggle with this once in a while.',
    next_steps: 'To improve your confidence, try to start asking more questions in practice. Let your coach know how you’re doing and how you’re feeling. It will also help to think positive by writing down three good things you did at each practice or game. If you don’t know, ask your coach to help! Finally, remember to focus on being the best athlete you can be regardless of what other people think, say, or do.',
  },
  {
    name: YouthCluster.SelfConfidence,
    language: Language.English,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Your Self-Confidence score was higher than other youth athletes. Self-confidence is your beliefs about yourself and your abilities. This score means you probably feel like you are good enough just the way you are. You probably keep a positive mindset and focus. You also probably know when to use healthy coping skills. Athletes with high scores in this area almost always focus on what is important, on and off the field.',
    next_steps: 'You can keep your self-confidence high by asking questions to coaches, teammates, and parents to improve your view of yourself and your abilities. Finally, remember to focus on being the best athlete you can be regardless of what other people think, say, or do.',
  },
  {
    name: YouthCluster.TeamCulture,
    language: Language.English,
    minPercentile: 0,
    maxPercentile: 20,
    meaning: 'Your Team Culture score tells us you feel like your teammates or community may not be supporting you enough on and off the field. You may feel distant from your team at times. Those with above average scores feel as though their value does not depend on whether they win or lose.',
    next_steps: 'To work on this area, reflect on your role on the team and consider how your role serves as an important piece. Identify your strengths and unique abilities and how you can bring that into training or competition. Get to know members of your team outside of training and competition when given the opportunity. You may also consider speaking with your coach or teammates to share how you’ve been feeling, and explore opportunities for the team to strengthen its relationships with one another.',
  },
  {
    name: YouthCluster.TeamCulture,
    language: Language.English,
    minPercentile: 30,
    maxPercentile: 80,
    meaning: 'Your Team Culture score is in the average range in comparison to other youth athletes, which means you may feel supported at times, but there may be moments where you feel disconnected from your team or community. It may be that you feel supported by your team, but not your family, or vice versa. There is also a chance that you feel supported by your team and family but it depends on how you perform.',
    next_steps: 'To improve your score in this area, think about who you feel supported by, when you feel the most supported, and when you feel like your needs were met once you spoke up. Once you have thought about these things, notice the times you felt cared about as an athlete and person. This can help you become aware of opportunities to connect with others outside of training or competition on a more personal level. Take what you thought about by noticing moments where you may try to keep yourself far from others versus opening up to others.',
  },
  {
    name: YouthCluster.TeamCulture,
    language: Language.English,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Your Team Culture score is higher than most youth athletes. Youth athletes who score highly in this category tend to have strong, meaningful relationships with their team and community. You likely feel that people care about your wellbeing and see you as more than an athlete. You are likely to be in an environment that has open and honest conversations with others, and feel heard and valued for who you are. Youth athletes who score high in this category also feel they are valued by others no matter how they perform.',
    next_steps: 'To keep your score high in this area, continue to value those on your team and keep communicating with coaches, friends, and family. Being a kind voice on your team can be like a domino effect, allowing your teammates to feel they are being listened to and supported which can bring your team closer together. In addition, you should try to talk about your appreciation to those who have supported you during your time as an athlete and as a person.',
  },
  {
    name: YouthCluster.HealthBehaviors,
    language: Language.English,
    minPercentile: 0,
    maxPercentile: 20,
    meaning: 'Your Health Behaviors score is in the below average range compared to other youth athletes, which means you are trying to balance sport and other areas of your life. Being dedicated to your sport can be time consuming which is why it is important to not let other important areas slip away, such as your sleep and nutrition. Youth athletes with high scores in this area feel a good balance between life and sport, limit their social media use, have good sleep habits, and eat well.',
    next_steps: 'To improve your scores in this area, ask yourself what areas need the most improvement when it comes to finding the right balance between sports, friends, family, and other hobbies. Consider dialing in your sleep routine by putting your phone away, going to bed and waking up at the same time every day, and eating good quality meals. You can also be intentional with recovery days to make sure you’re taking time outside of sport to rest.',
  },
  {
    name: YouthCluster.HealthBehaviors,
    language: Language.English,
    minPercentile: 30,
    maxPercentile: 80,
    meaning: 'Your Health Behaviors score is in the average range in comparison to other youth athletes, which means you are likely doing some things that are important to physical health and mental health outside of sport, but have some areas to improve on. Youth athletes with high scores in this area feel a good balance between life and sport, limit their social media use, have good sleep habits, and eat well.',
    next_steps: 'To improve scores in this area, ask yourself what areas need the most improvement when it comes to finding the right balance between sports, friends, family, and other hobbies. Consider changing your sleep routine by putting your phone away, going to bed and waking up at the same time every day, and eating good quality meals. You can also choose to have recovery days to make sure you’re taking time outside of sport to rest.',
  },
  {
    name: YouthCluster.HealthBehaviors,
    language: Language.English,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Your Health Behaviors score is in the above average range in comparison to other youth athletes, which means you are likely doing things that are important to physical health and mental health outside of sport. Youth athletes with high scores in this area feel a good balance between life and sport, limit social media use, have good sleep habits, and eat well.',
    next_steps: 'To maintain scores in this area, ask yourself what areas you can continue to improve on when it comes to finding the right balance between sports, friends, family, and other hobbies. Keep up with your sleep routine even more than you’ve already done. You can also choose to have recovery days to make sure you’re taking time outside of sport to rest.',
  },
]
