import { MindBalanceAdultCluster, Language } from "../types";

export const clusters = [
  {
    name: MindBalanceAdultCluster.ResilientMindset,
    language: Language.English,
    label: 'RESILIENT MINDSET',
    summaryPageDescription: 'An athlete\'s ability to be kind and understanding toward oneself when faced with difficulties, and to embrace challenges.',
    description: 'An athlete\'s ability to be kind and understanding toward oneself when faced with difficulties, and to embrace challenges.',
    funFact: 'In a sample of 409 athletes, Resilient Mindset scores were the largest predictor of stress management (compared to the other four Mindset clusters). As resilient mindset scores increased, stress management scores also increased.',
    relevantModules: '',
  },
  {
    name: MindBalanceAdultCluster.MentalSkills,
    language: Language.English,
    label: 'MENTAL SKILLS',
    summaryPageDescription: 'An athlete\'s use of skills such as goal setting, mental preparation, and the use of mindfulness, imagery, and present-moment focus.',
    description: 'An athlete\'s use of skills such as goal setting, mental preparation, and the use of mindfulness, imagery, and present-moment focus.',
    funFact: 'Athletes with stronger mental skills tend to possess greater mindfulness abilities. A strong positive correlation was found between athletes\' Mental Skills and Mindful Awareness scores.',
    relevantModules: '',
  },
  {
    name: MindBalanceAdultCluster.TeamSupport,
    language: Language.English,
    label: 'TEAM ENVIRONMENT',
    summaryPageDescription: 'An athlete\'s relationship with teammates and coaches, as well as whether the athlete feels they have a voice on their team.',
    description: 'An athlete\'s relationship with teammates and coaches, as well as whether the athlete feels they have a voice on their team.',
    funFact: 'Athletes with higher team environment scores are likely to report significantly lower levels of psychological distress and burnout in sport.',
    relevantModules: '',
  },
  {
    name: MindBalanceAdultCluster.HealthHabits,
    language: Language.English,
    label: 'HEALTH HABITS',
    summaryPageDescription: 'An athlete\'s quality of sleep and nutrition, following injury prevention guidelines, and getting ample rest & recovery.',
    description: 'An athlete\'s quality of sleep and nutrition, following injury prevention guidelines, and getting ample rest & recovery.',
    funFact: 'Athletes who have better health habits tend to have less physical and emotional exhaustion. A strong correlation was found between athletes\' Health Habits and their physical and emotional exhaustion scores.',
    relevantModules: '',
  },
  {
    name: MindBalanceAdultCluster.WellnessAccountability,
    language: Language.English,
    label: 'WELLNESS ACCOUNTABILITY',
    summaryPageDescription: 'An athlete\'s accountability in using mindset tools and resources to keep their mind optimal and resilient.',
    description: 'An athlete\'s accountability in using mindset tools and resources to keep their mind optimal and resilient.',
    funFact: 'Athletes who are better at holding themselves accountable also tend to feel a stronger sense of purpose. A strong correlation was found between athletes\' accountability and their self-compassion and purpose scores.',
    relevantModules: '',
  },
  {
    name: MindBalanceAdultCluster.ResilientMindset,
    language: Language.Spanish,
    label: 'MENTALIDAD RESILIENTE',
    summaryPageDescription: 'La capacidad de un atleta para ser amable y comprensivo consigo mismo cuando se enfrenta a dificultades, y para aceptar desafíos.',
    description: 'La capacidad de un atleta para ser amable y comprensivo consigo mismo cuando se enfrenta a dificultades, y para aceptar desafíos.',
    funFact: 'En una muestra de 409 atletas, las puntuaciones de Mentalidad Resiliente fueron el mayor predictor del manejo del estrés (en comparación con los otros cuatro clusters de Mentalidad). A medida que aumentaron las puntuaciones de mentalidad resiliente, también aumentaron las puntuaciones de manejo del estrés.',
    relevantModules: '',
  },
  {
    name: MindBalanceAdultCluster.MentalSkills,
    language: Language.Spanish,
    label: 'HABILIDADES MENTALES',
    summaryPageDescription: 'El uso de habilidades por parte de un atleta, como el establecimiento de metas, la preparación mental y el uso de la atención plena, la imaginería y el enfoque en el momento presente.',
    description: 'El uso de habilidades por parte de un atleta, como el establecimiento de metas, la preparación mental y el uso de la atención plena, la imaginería y el enfoque en el momento presente.',
    funFact: 'Los atletas con habilidades mentales más fuertes tienden a poseer mayores habilidades de atención plena. Se encontró una fuerte correlación positiva entre las puntuaciones de Habilidades Mentales y Conciencia Plena de los atletas.',
    relevantModules: '',
  },
  {
    name: MindBalanceAdultCluster.TeamSupport,
    language: Language.Spanish,
    label: 'AMBIENTE DE EQUIPO',
    summaryPageDescription: 'La relación de un atleta con compañeros de equipo y entrenadores, así como si el atleta siente que tiene voz en su equipo.',
    description: 'La relación de un atleta con compañeros de equipo y entrenadores, así como si el atleta siente que tiene voz en su equipo.',
    funFact: 'Los atletas con puntuaciones más altas de ambiente de equipo tienen más probabilidades de reportar niveles significativamente más bajos de angustia psicológica y agotamiento en el deporte.',
    relevantModules: '',
  },
  {
    name: MindBalanceAdultCluster.HealthHabits,
    language: Language.Spanish,
    label: 'HÁBITOS DE SALUD',
    summaryPageDescription: 'La calidad del sueño y la nutrición de un atleta, siguiendo las pautas de prevención de lesiones y obteniendo suficiente descanso y recuperación.',
    description: 'La calidad del sueño y la nutrición de un atleta, siguiendo las pautas de prevención de lesiones y obteniendo suficiente descanso y recuperación.',
    funFact: 'Los atletas que tienen mejores hábitos de salud tienden a tener menos agotamiento físico y emocional. Se encontró una fuerte correlación entre los Hábitos de Salud de los atletas y sus puntuaciones de agotamiento físico y emocional.',
    relevantModules: '',
  },
  {
    name: MindBalanceAdultCluster.WellnessAccountability,
    language: Language.Spanish,
    label: 'RESPONSABILIDAD DEL BIENESTAR',
    summaryPageDescription: 'La responsabilidad de un atleta en el uso de herramientas y recursos de mentalidad para mantener su mente óptima y resiliente.',
    description: 'La responsabilidad de un atleta en el uso de herramientas y recursos de mentalidad para mantener su mente óptima y resiliente.',
    funFact: 'Los atletas que son mejores para responsabilizarse también tienden a sentir un sentido más fuerte de propósito. Se encontró una fuerte correlación entre la responsabilidad de los atletas y sus puntuaciones de autocompasión y propósito.',
    relevantModules: '',
  },
];

