import { Cluster, Language } from "../types";

export const clusters = [
  {
    name: Cluster.GrowthMindset,
    language: Language.English,
    label: 'Resilient Mindset',
    summaryPageDescription: 'An athlete’s ability to be kind and understanding toward oneself when faced with difficulties, and to embrace challenges.',
    description: 'A resilient mindset is an athlete’s ability to embrace challenges, and to be compassionate toward oneself when faced with difficulties.',
    funFact: 'In a sample of 409 athletes, Resilient Mindset scores were the largest predictor of stress management (compared to the other four Mindset clusters). As Resilient Mindset scores increased, stress management scores also increased.',
    relevantModules: 'Focus and Confidence modules',
  },
  {
    name: Cluster.MentalSkills,
    language: Language.English,
    label: 'Mental Skills',
    summaryPageDescription: 'Skills such as goal setting, mental preparation, and the use of mindfulness, imagery, and present-moment focus.',
    description: 'Mental skills are your toolkit for overall mental readiness. They include skills such as goal setting, mental preparation before competition, and the use of mindfulness, imagery, and present-moment focus.',
    funFact: 'Athletes with stronger mental skills tend to possess greater mindfulness abilities. A strong positive correlation was found between athletes’ Mental Skills and Mindful Awareness scores.',
    relevantModules: 'Imagery and Mindfulness modules',
  },
  {
    name: Cluster.TeamSupport,
    language: Language.English,
    label: 'Team Environment',
    summaryPageDescription: 'The strength of relationships with teammates and coaches, as well as whether the athlete feels they have a voice on the team.',
    description: 'Team environment reflects the nature of your relationships with teammates and coaches, as well as whether you feel you have a voice on your team.',
    funFact: 'Athletes with higher team environment scores are likely to report significantly lower levels of psychological distress and burnout in sport.',
    relevantModules: 'Confidence module',
  },
  {
    name: Cluster.HealthHabits,
    language: Language.English,
    label: 'Health Habits',
    summaryPageDescription: 'Getting high quality sleep and nutrition, following injury prevention guidelines, and getting ample rest & recovery.',
    description: 'Your health habits refer to the routines you maintain to ensure overall mental and physical wellness. They include getting high quality sleep and nutrition, following injury prevention guidelines, and getting ample rest and recovery.',
    funFact: 'Athletes who have better health habits tend to have less physical and emotional exhaustion. A strong correlation was found between athletes’ Health Habits and their physical and emotional exhaustion scores.',
    relevantModules: 'Mindfulness module',
  },
  {
    name: Cluster.SelfReflection,
    language: Language.English,
    label: 'Wellness Accountability',
    summaryPageDescription: 'Being proactively accountable to using mindset tools and resources to keep your mind optimal and resilient.',
    description: 'This area of wellness and performance reflects being proactively accountable to using mindset tools and resources to keep your mind optimal and resilient.',
    funFact: 'Athletes who are better at holding themselves accountable also tend to feel a stronger sense of purpose. A strong correlation was found between athletes’ accountability and their self-compassion and purpose scores.',
    relevantModules: 'Emotional Regulation and Motivation modules',
  },
  {
    name: Cluster.GrowthMindset,
    language: Language.Spanish,
    label: 'Mentalidad Resiliente',
    summaryPageDescription: 'La capacidad de un atleta de ser amable y comprensivo consigo mismo cuando se enfrenta a dificultades y de aceptar los desafíos.',
    description: 'Una mentalidad resiliente es la capacidad de un atleta para aceptar desafíos y ser compasivo con uno mismo cuando enfrenta dificultades.',
    funFact: 'En una muestra de 409 atletas, las puntuaciones de Mentalidad Resiliente fueron el mayor predictor del manejo del estrés (en comparación con los otros cuatro grupos de Mentalidad). A medida que aumentaron las puntuaciones de mentalidad resiliente, también aumentaron las puntuaciones de manejo del estrés.',
    relevantModules: 'los módulos de enfoque y confianza',
  },
  {
    name: Cluster.MentalSkills,
    language: Language.Spanish,
    label: 'Habilidades Mentales',
    summaryPageDescription: 'Habilidades como el establecimiento de objetivos, la preparación mental y el uso de la atención plena, las imágenes y la concentración en el momento presente.',
    description: 'Habilidades como el establecimiento de objetivos, la preparación mental y el uso de la atención plena, las imágenes y la concentración en el momento presente.',
    funFact: 'Los atletas con habilidades mentales más fuertes tienden a poseer mayores habilidades de atención plena. Existe una fuerte correlación positiva entre las puntuaciones de habilidades mentales y conciencia plena de los atletas.',
    relevantModules: 'los módulos de Imágenes y Atención Plena',
  },
  {
    name: Cluster.TeamSupport,
    language: Language.Spanish,
    label: 'Ambiente de Equipo',
    summaryPageDescription: 'La solidez de las relaciones con los compañeros de equipo y los entrenadores, así como si el atleta siente que tiene voz en el equipo.',
    description: 'La solidez de las relaciones con los compañeros de equipo y los entrenadores, así como si el atleta siente que tiene voz en el equipo.',
    funFact: 'Es probable que los atletas con puntuaciones más altas en el ambiente de equipo reporten niveles significativamente más bajos de malestar psicológico y agotamiento en el deporte.',
    relevantModules: 'el módulo Confianza',
  },
  {
    name: Cluster.HealthHabits,
    language: Language.Spanish,
    label: 'Hábitos Saludables',
    summaryPageDescription: 'Dormir y nutrirse de alta calidad, seguir las pautas de prevención de lesiones y descansar y recuperarse lo suficiente.',
    description: 'Dormir y nutrirse de alta calidad, seguir las pautas de prevención de lesiones y descansar y recuperarse lo suficiente.',
    funFact: 'Los deportistas que tienen mejores hábitos de salud suelen tener menos cansancio físico y emocional. Se encontró una fuerte correlación entre los hábitos de salud de los atletas y sus puntuaciones de agotamiento físico y emocional.',
    relevantModules: 'el módulo Mindfulness',
  },
  {
    name: Cluster.SelfReflection,
    language: Language.Spanish,
    label: 'Wellness Accountability',
    summaryPageDescription: 'El uso de la autorreflexión, los recursos de salud mental y la apertura para hablar sobre la salud física y mental con los demás.',
    description: 'El uso de la autorreflexión, los recursos de salud mental y la apertura para hablar sobre la salud física y mental con los demás.',
    funFact: 'Los atletas que son mejores a la hora de responsabilizarse también tienden a tener un sentido de propósito más fuerte. Se encontró una fuerte correlación entre la responsabilidad de los atletas y sus puntuaciones de autocompasión y propósito.',
    relevantModules: 'los módulos de regulación emocional y motivación',
  },
];