import { StaffCluster, Language } from "../types";

export const clusters = [
  {
    name: StaffCluster.PerformanceMindset,
    language: Language.English,
    label: 'Performance Mindset',
    summaryPageDescription: 'A performance mindset is the extent to which staff members balance daily deliverables with long-term career goals and plans.',
    description: 'A performance mindset is the extent to which staff members balance daily deliverables with long-term career goals and plans.',
    funFact: '70% of respondents have a strong understanding of what drives or motivates them in the workplace.',
},
  {
    name: StaffCluster.MindfulIntention,
    language: Language.English,
    label: 'Mindful Intention',
    summaryPageDescription: 'Mindful intention is using skills such as task delegation, effective routines, boundary setting, and goal creation to support performance in the workplace.',
    description: 'Mindful intention is using skills such as task delegation, effective routines, boundary setting, and goal creation to support performance in the workplace.',
    funFact: 'Sport staff employees who score higher in mindful intention are more likely to be engaged in their work.',
},
  {
    name: StaffCluster.Recovery,
    language: Language.English,
    label: 'Recovery',
    summaryPageDescription: 'Recovery is a reflection of how staff members separate work responsibilities from other areas of life, how and whether they recharge and take time off, and how they manage expectations outside of the office.',
    description: 'Recovery is a reflection of how staff members separate work responsibilities from other areas of life, how and whether they recharge and take time off, and how they manage expectations outside of the office.',
    funFact: 'Sport staff employees who score high in recovery tend to show lower levels of psychological distress.',
},
  {
    name: StaffCluster.TeamCulture,
    language: Language.English,
    label: 'Team Culture',
    summaryPageDescription: 'Team Culture is how much an employee feels supported and valued in the workplace, as well as the quality of relationships with colleagues and supervisors.',
    description: 'Team Culture is how much an employee feels supported and valued in the workplace, as well as the quality of relationships with colleagues and supervisors.',
    funFact: 'Sport staff employees who score higher in Team Culture also tend to score higher in their work dedication.',
  },
  {
    name: StaffCluster.RelationalDynamics,
    language: Language.English,
    label: 'Relational Dynamics',
    summaryPageDescription: 'Relational dynamics is one\'s ability to trust their colleagues, effectively communicate with team members, and maintain flexibility and openness to new ideas and perspectives.',
    description: 'Relational dynamics is one\'s ability to trust their colleagues, effectively communicate with team members, and maintain flexibility and openness to new ideas and perspectives.',
    funFact: '55% of respondents consistently look for opportunities to work with colleagues who have different ideas and mindsets.',
  },
]

export const percentileInterpretationStaff = [
  {
    name: StaffCluster.PerformanceMindset,
    language: Language.English,
    minPercentile: 0,
    maxPercentile: 20,
    meaning: 'Your score suggests you may not regularly consider how goal setting, task prioritization, or professional development can affect the long-game of wellness and performance. You may have some difficulties finding motivation, adapting, or practicing persistence during times of challenge or adversity.',
    next_steps: 'To improve your Performance Mindset score, first reflect on what components of your work bring you the most energy and enthusiasm. Remind yourself of the mission of your work (also known as your “why”). Then, reflect on some of the challenges of your current job. Identify which aspects of your job you have control over and which you do not have control over. Ask yourself and others how you can better prepare for or respond to work-related challenges, including the ways in which you can practice flexibility, when needed. Finally, review your to-do lists and set small, attainable goals each week to prioritize what’s important and to stay on track while balancing goals and wellness.',
  },
  {
    name: StaffCluster.PerformanceMindset,
    language: Language.English,
    minPercentile: 30,
    maxPercentile: 80,
    meaning: 'Your score suggests you may understand how goal setting, task prioritization, or professional development can affect the long-game of wellness and performance–but you may not yet be acting on these things regularly. You may typically find motivation, adapt, and practice persistence but may find it harder to do this during particularly stressful or challenging times. People with scores in your range typically set work related goals to stay grounded and to focus on the bigger picture. Those who score similarly to you also remind themselves of their “why” for working in their chosen industry or profession.',
    next_steps: 'To improve your Performance Mindset score, first reflect on what components of your work bring you the most energy and enthusiasm. Remind yourself of the mission of your work (also known as your “why”). Then, reflect on some of the challenges of your current job. Identify which aspects of your job you have control over and which you do not have control over. Ask yourself and others how you can better prepare for or respond to work-related challenges, including the ways in which you can practice flexibility when needed. Finally, review your to-do lists and set small attainable goals each week to prioritize what’s important and to stay on track while balancing goals and wellness.',
  },
  {
    name: StaffCluster.PerformanceMindset,
    language: Language.English,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Your score suggests you actively prepare for and adapt to challenges. You likely set work related goals to remain focused on the bigger picture. Those who score similarly to you regularly remind themselves of their “why” for working in the sports industry. Employees who score high in this area typically have a strong passion for their work and understand what drives and motivates them.',
    next_steps: 'To maintain a high Performance Mindset score, step back to reflect on what components of your work bring you the most energy and enthusiasm. Remind yourself of the mission of your work (also known as your “why”). Then, reflect on some of the challenges of your current job. Identify which aspects of your job you have control over and which you do not have control over. Ask yourself and others how you can better prepare for or respond to work-related challenges, including the ways in which you can practice flexibility when needed. Finally, review your to-do lists and set small attainable goals each week to prioritize what’s important and to stay on track while balancing goals and wellness.',
  },
  {
    name: StaffCluster.MindfulIntention,
    language: Language.English,
    minPercentile: 0,
    maxPercentile: 20,
    meaning: 'This score suggests you may focus on your personal development occasionally, but may be feeling stuck or may struggle to prioritize your own personal and professional growth due to other job demands. You may also experience challenges to remain fully present and centered throughout the day. Those with high scores on this scale are almost always intentional with the tasks they take on. They celebrate small wins, and they set clear and realistic work goals for themselves on a daily or weekly basis. They are also likely to prioritize their own health and wellness by maintaining a well-balanced diet and a meaningful exercise schedule.',
    next_steps: 'To improve your Mindful Intention score, begin by asking yourself where most of your energy is directed at work. Then, ask yourself whether the time spent on those demands reflects the importance of each task. Consider making your goals SMART (specific, measurable, attainable, relevant, and time-based). Having routines that you can control, such as coming to work early or packing a nutritious meal for lunch, can also help improve your mindful intention score. Consider making meetings 25 or 50 minutes (rather than 30 or 60) to allow for time to recenter and check in with yourself throughout the day. At the end of each week, reflect on whether the tasks you took on aligned with your overall terms.',
  },
  {
    name: StaffCluster.MindfulIntention,
    language: Language.English,
    minPercentile: 30,
    maxPercentile: 80,
    meaning: 'This score suggests you may focus on your personal development when you have the opportunity, but you may struggle to prioritize your personal and professional development when work-related demands become really high. You may be able to be fully present and centered throughout the day when work is going well, but may not have a specific practice or routine for checking in with yourself. Those with high scores on this scale are almost always intentional with the tasks they take on. They celebrate small wins, and they set clear and realistic work goals for themselves on a daily or weekly basis. They are also likely to prioritize their own health and wellness by maintaining a well-balanced diet and a meaningful exercise schedule.',
    next_steps: 'To improve your Mindful Intention score, begin by asking yourself where most of your energy is directed at work. Then, ask yourself whether the time spent on those demands reflects the importance of each task. It may also be helpful for you to make your goals SMART (specific, measurable, attainable, relevant, and time-based). Having routines that you can control, like coming to work early or packing a nutritious meal for lunch, can also help improve your mindful intention score. Consider making meetings 25 or 50 minutes (rather than 30 or 60) to allow for time to recenter and check in with yourself throughout the day. At the end of each week, reflect on whether the tasks you took on aligned with your overall terms.',
  },
  {
    name: StaffCluster.MindfulIntention,
    language: Language.English,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'This score suggests you likely prioritize your personal development, even when work-related demands become high. You  are likely fully present and centered throughout your work day. Those with high scores on this scale are very intentional about the tasks they take on. They celebrate small wins, and they set clear and realistic work goals for themselves on a daily or weekly basis. They are also likely to prioritize their own health and wellness by maintaining a well-balanced diet and a meaningful exercise schedule.',
    next_steps: 'To maintain a high Mindful Intention score, regularly ask yourself where you direct most of your energy at work. Then, ask yourself whether the time spent on those demands reflects the importance of each task. Make sure the goals you set for yourself are SMART (specific, measurable, attainable, relevant, and time-based). Having routines that you can control, like coming to work early or packing a nutritious meal for lunch, can also help improve your mindful intention score. Consider making meetings 25 or 50 minutes (rather than 30 or 60) to allow for time to recenter and check in with yourself throughout the day. At the end of each week, reflect on whether the tasks you took on aligned with your overall terms.',
  },
  {
    name: StaffCluster.Recovery,
    language: Language.English,
    minPercentile: 0,
    maxPercentile: 20,
    meaning: 'Your score suggests you may struggle to separate work responsibilities from other areas of your life. You may find that it’s a challenge to manage work expectations or to set boundaries when you are not in the office. Staff members with scores similar to yours tend not to use their PTO (paid time off) and may not take time to disconnect from work when needed. Though it can be difficult to disconnect from high performance work environments, research shows it is important to separate work life from personal life when necessary. Those with high scores in this area tend to set aside time for their personal health and well-being, regularly engage in hobbies unrelated to work, and feel as though they have good work/life balance.',
    next_steps: 'To increase your scores in this area, consider the ways in which you can begin to set work-related boundaries such as limiting your phone and email access. Consider creating an end-of-day routine that will allow you to recover and be more present with loved ones after your work day.',
  },
  {
    name: StaffCluster.Recovery,
    language: Language.English,
    minPercentile: 30,
    maxPercentile: 80,
    meaning: 'Your score suggests you can generally separate work responsibilities from other areas of your life, but you may not have clear boundaries after hours or while out of the office. Staff members with scores similar to yours likely take PTO (paid time off) on occasion, but may not always take time to disconnect from work when needed. Though it can be difficult to disconnect from high performance work environments, research shows it is important to separate work life from personal life when able. Staff members with high scores in this area tend to intentionally set aside time for their personal health and well-being, regularly engage in hobbies unrelated to work, and feel as though they have good work/life balance.',
    next_steps: 'To increase your scores in this area, consider the ways in which you can begin to set work-related boundaries by limiting your phone and email access. Consider creating an end-of-day routine that will allow you to recover and be more present with loved ones after your work day.',
  },
  {
    name: StaffCluster.Recovery,
    language: Language.English,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'You likely feel that you consistently manage expectations and responsibilities when you are not in the office. Staff members who score similar to you are likely to use their PTO (paid time off) to step away from work and recharge. They are likely to intentionally set aside time for themselves to focus on their personal health and well-being. Those with high scores also likely understand when they need to take time away to recenter.',
    next_steps: 'To maintain high scores in this area, consider the situations in which boundaries between work and life become blurred. Consider limited phone and email access after hours if you do not already do so. You may also consider creating an end-of-day routine that will allow you to recover and be more present with loved ones after your work day.',
  },
  {
    name: StaffCluster.TeamCulture,
    language: Language.English,
    minPercentile: 0,
    maxPercentile: 20,
    meaning: 'People with scores similar to yours may not feel they have clear roles and responsibilities, tend to feel taken for granted, and may not feel as though their work is meaningful. Those with low scores tend to have distant and somewhat impersonal relationships with their supervisors, which can limit free expression or psychological safety in the workplace.',
    next_steps: 'To improve your Team Culture score, talk through interpersonal conflicts with a trusted colleague or co-worker. Doing so increases psychological safety in the workplace and limits feelings of resentment. Set aside time to reflect on the resources you need to succeed at work, the clarity of your roles and responsibilities, and your work priorities. Discuss murky areas with a supervisor or a mentor. It may also help to have a conversation with your supervisor about the nature of your relationship. Ask your supervisor for feedback on your performance and interpersonal style, and apply that feedback to meetings and daily interactions with others.',
  },
  {
    name: StaffCluster.TeamCulture,
    language: Language.English,
    minPercentile: 30,
    maxPercentile: 80,
    meaning: 'People with scores similar to yours generally feel they have clear roles and responsibilities, rarely feel taken for granted, and generally feel as though their work is meaningful. People with scores in your range tend to have good working relationships with their supervisors, but may hesitate to open up when work or life becomes notably difficult.',
    next_steps: 'To improve your Team Culture score, talk through interpersonal conflicts with a trusted colleague or co-worker. Doing so increases psychological safety in the workplace and limits feelings of resentment. Set aside time to reflect on the resources you need to succeed at work, the clarity of your roles and responsibilities, and your work priorities. Discuss murky areas with a supervisor or a mentor. It may also help to have a conversation with your supervisor about the nature of your relationship. Ask your supervisor for feedback on your performance and interpersonal style, and apply that feedback to meetings and daily interactions with others.',
  },
  {
    name: StaffCluster.TeamCulture,
    language: Language.English,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'People with scores similar to yours typically feel they have clear roles and responsibilities, do not feel taken for granted, and often feel as though their work is meaningful. Those with high scores tend to have close working relationships with their supervisors, and are likely able to open up to supervisors when needed to ask for help, feedback, or additional resources/support.',
    next_steps: 'To maintain a high Team Culture score, continue to talk through interpersonal conflicts with a trusted colleague or co-worker. Doing so increases psychological safety in the workplace and limits feelings of resentment. Set aside time to reflect on the resources you need to succeed at work, the clarity of your roles and responsibilities, and your work priorities. Discuss murky areas with a supervisor or a mentor. It may also help to have a conversation with your supervisor about the nature of your relationship. Ask your supervisor for feedback on your performance and interpersonal style, and apply that feedback to meetings and daily interactions with others.',
  },
  {
    name: StaffCluster.RelationalDynamics,
    language: Language.English,
    minPercentile: 0,
    maxPercentile: 20,
    meaning: 'Your score suggests this may be a growth area for you. Those with scores similar to yours may have a few close colleagues, but may not feel comfortable engaging in free dialogues with colleagues or asking questions when needed. You may not have a common language or process for discussing change in your current work environment and may not regularly receive honest or constructive feedback from colleagues or supervisors. Those with high scores in this area generally trust in their team’s abilities, are patient with others when discussing areas in need of improvement, and have a shared understanding with colleagues.',
    next_steps: 'To improve your score in this area, consider having a conversation with your supervisor or a trusted colleague to seek feedback. Ask for feedback regarding your communication style, your openness to learning from others, and the role you typically take on a team. You may make an effort to actively get to know other team members or colleagues at professional networking events or by stepping in for a new opportunity you may not otherwise consider.',
  },
  {
    name: StaffCluster.RelationalDynamics,
    language: Language.English,
    minPercentile: 30,
    maxPercentile: 80,
    meaning: 'Those with scores similar to yours may have a number of close colleagues and may generally feel comfortable engaging in free dialogues with colleagues or asking questions when needed. You may receive honest or constructive feedback from colleagues or supervisors, but may not have a regular process for discussing feedback or discussing change. Those with high scores in this area generally trust in their team’s abilities, are patient with others when discussing areas in need of improvement, and have a shared understanding with colleagues.',
    next_steps: 'To improve your score in this area, consider having a conversation with your supervisor or a trusted colleague to seek feedback. Ask for feedback regarding your communication style, your openness to learning from others, and the role you typically take on a team. You may make an effort to actively get to know other team members or colleagues at professional networking events or by stepping in for a new opportunity you may not otherwise consider.',
  },
  {
    name: StaffCluster.RelationalDynamics,
    language: Language.English,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Those with scores similar to yours are likely to have several close colleagues, and are typically comfortable engaging in free dialogues with them or asking questions when needed. You likely have a common language or process for discussing change in your current work environment, allowing you to regularly receive honest or constructive feedback from colleagues or supervisors. Those with high scores in this area generally trust in their team’s abilities, are patient with others when discussing areas in need of improvement, and have a shared understanding with colleagues.',
    next_steps: 'To maintain your score in this area, ask for feedback regarding your communication style, as well as your openness to learning from others. Reflect on the role you typically take on a team and lean into opportunities for growth. Make a continued effort to actively get to know other team members or colleagues at professional networking events or by stepping in for a new opportunity you may not otherwise consider.',
  },
]
