import { MindBalanceCluster, Language } from "../types";

export const clusters = [
  {
    name: MindBalanceCluster.GrowthMindset,
    language: Language.English,
    label: 'Growth Mindset',
    summaryPageDescription: 'An athlete\'s ability to celebrate signs of progress throughout the year, feel empowered to try new things, and embrace challenges.',
    description: 'An athlete\'s ability to celebrate signs of progress throughout the year, feel empowered to try new things, and embrace challenges.',
    funFact: 'Athletes who scored higher on Growth Mindset also scored lower on perceived levels of stress.',
    relevantModules: '',
  },
  {
    name: MindBalanceCluster.SelfConfidence,
    language: Language.English,
    label: 'Self-Confidence',
    summaryPageDescription: 'An athlete\'s self-awareness and openness to ask for help when needed. This also includes a willingness to ask questions, a healthy way to handle pressure from others, and a love for their sport.',
    description: 'An athlete\'s self-awareness and openness to ask for help when needed. This also includes a willingness to ask questions, a healthy way to handle pressure from others, and a love for their sport.',
    funFact: 'Athletes who report higher levels of Self-confidence are more likely to report higher levels of meaning and purpose.',
    relevantModules: '',
  },
  {
    name: MindBalanceCluster.TeamCulture,
    language: Language.English,
    label: 'Team Culture',
    summaryPageDescription: 'An athlete\'s sense of feeling valued on a team regardless of performance, playing for a team that focuses on more than wins and losses, and choosing clubs that create supportive and positive environments.',
    description: 'An athlete\'s sense of feeling valued on a team regardless of performance, playing for a team that focuses on more than wins and losses, and choosing clubs that create supportive and positive environments.',
    funFact: 'Athletes who scored higher on Team Culture are more likely to report higher levels of life satisfaction.',
    relevantModules: '',
  },
  {
    name: MindBalanceCluster.HealthBehaviors,
    language: Language.English,
    label: 'Health Behaviors',
    summaryPageDescription: 'An athlete\'s commitment to maintaining mental and physical health. This category includes sleep, managing social media use, and taking rest days.',
    description: 'An athlete\'s commitment to maintaining mental and physical health. This category includes sleep, managing social media use, and taking rest days.',
    funFact: 'Athletes who scored higher on Health Behaviors also scored higher on their overall mental and physical health.',
    relevantModules: '',
  },
  {
    name: MindBalanceCluster.GrowthMindset,
    language: Language.Spanish,
    label: 'Mentalidad de Crecimiento',
    summaryPageDescription: 'La capacidad de un atleta para celebrar los signos de progreso a lo largo del año, sentirse empoderado para probar cosas nuevas y aceptar desafíos.',
    description: 'La capacidad de un atleta para celebrar los signos de progreso a lo largo del año, sentirse empoderado para probar cosas nuevas y aceptar desafíos.',
    funFact: 'Los atletas que obtuvieron una puntuación más alta en Mentalidad de Crecimiento también obtuvieron una puntuación más baja en los niveles percibidos de estrés.',
    relevantModules: '',
  },
  {
    name: MindBalanceCluster.SelfConfidence,
    language: Language.Spanish,
    label: 'Autoconfianza',
    summaryPageDescription: 'La autoconciencia de un atleta y su apertura para pedir ayuda cuando sea necesario. Esto también incluye la voluntad de hacer preguntas, una forma saludable de manejar la presión de los demás y el amor por su deporte.',
    description: 'La autoconciencia de un atleta y su apertura para pedir ayuda cuando sea necesario. Esto también incluye la voluntad de hacer preguntas, una forma saludable de manejar la presión de los demás y el amor por su deporte.',
    funFact: 'Los atletas que reportan niveles más altos de Autoconfianza tienen más probabilidades de reportar niveles más altos de significado y propósito.',
    relevantModules: '',
  },
  {
    name: MindBalanceCluster.TeamCulture,
    language: Language.Spanish,
    label: 'Cultura de Equipo',
    summaryPageDescription: 'El sentido de un atleta de sentirse valorado en un equipo independientemente del rendimiento, jugar para un equipo que se enfoca en más que victorias y derrotas, y elegir clubes que creen entornos de apoyo y positivos.',
    description: 'El sentido de un atleta de sentirse valorado en un equipo independientemente del rendimiento, jugar para un equipo que se enfoca en más que victorias y derrotas, y elegir clubes que creen entornos de apoyo y positivos.',
    funFact: 'Los atletas que obtuvieron una puntuación más alta en Cultura de Equipo tienen más probabilidades de reportar niveles más altos de satisfacción con la vida.',
    relevantModules: '',
  },
  {
    name: MindBalanceCluster.HealthBehaviors,
    language: Language.Spanish,
    label: 'Comportamientos Saludables',
    summaryPageDescription: 'El compromiso de un atleta con el mantenimiento de la salud mental y física. Esta categoría incluye el sueño, la gestión del uso de las redes sociales y la toma de días de descanso.',
    description: 'El compromiso de un atleta con el mantenimiento de la salud mental y física. Esta categoría incluye el sueño, la gestión del uso de las redes sociales y la toma de días de descanso.',
    funFact: 'Los atletas que obtuvieron una puntuación más alta en Comportamientos Saludables también obtuvieron una puntuación más alta en su salud mental y física general.',
    relevantModules: '',
  },
];

