export const percentileInterpretation = [
  {
    name: 'growth_mindset',
    minPercentile: 0,
    maxPercentile: 30,
    meaning: 'Your Growth Mindset score is in the below average range compared to other athletes at your level, which suggests you may be quite hard on yourself. Athletes with scores similar to you often seek perfection in sport and become held back by negative thoughts that arise while training and competing. You may set high expectations for yourself and feel pressure to succeed. You may think your self-worth is based on your performance or abilities. This pattern of thinking can lead to fear of failure, rigidity, self-judgment, and feelings of anxiety when pushed outside of your comfort zone.',
    next_steps: 'To improve scores in this area, approach your mistakes with curiosity. Acknowledge the imperfect moments and frame these imperfections as learning opportunities to search for ways of growth. It can be hard to challenge these thoughts, but by becoming more aware of your inner dialogue, you can start to deconstruct your inner critic and rebuild an inner dialogue that is more likely to support your growth.',
  },
  {
    name: 'growth_mindset',
    minPercentile: 40,
    maxPercentile: 70,
    meaning: 'Your Growth Mindset score is in the average range compared to other athletes at your level, which suggests that you may support yourself during successes and failures, but there is room to grow by giving yourself a break when you don’t meet your expectations. On one hand, your thoughts might be constructive and understanding, but on the other hand they may be destructive and lead to being overly critical or harsh on yourself, allowing little margin for error.\n\nAthletes with high scores in this area consistently believe in themselves and their abilities. They can quickly recover from mistakes and negative thoughts that come up during training and competition. They also understand that their self-worth is not defined by their performance in sport. You may have these views occasionally, but may waiver depending on the situation.',
    next_steps: 'To lean into this growth area, check yourself when you become critical of your mistakes and ask yourself whether such thoughts support your growth. When you notice your inner critic, ask yourself, “What is going well? What is worth improving?” Finally, create a self-care routine that helps you recalibrate after a long day of training or competition. Then, maintain it!',
  },
  {
    name: 'growth_mindset',
    minPercentile: 80,
    maxPercentile: 100,
    meaning: 'This score is in the above average range compared to other professional athletes, which suggests that you are typically kind and understanding with yourself when faced with mistakes, difficulties, and adversity. Athletes who score highly in this area typically believe in themselves and their abilities. They are usually able to let go of mistakes and negative thoughts that arise during training and competition. They also understand that their self-worth is not defined by their performance in sport.',
    next_steps: 'To continue to maintain high levels of a growth mindset, practice skills such as mindfulness when you face adversity. Set an intentional routine of self-care that is meaningful and replenishing. Remember, imperfection is a gateway toward improvement. To elevate your growth mindset, it is critical to acknowledge that adversity is inevitable and serve as opportunities to grow in sport.',
  },
  {
    name: 'mental_skills',
    minPercentile: 0,
    maxPercentile: 30,
    meaning: 'Your Mental Skills score is in the below average range in comparison to other athletes at your level, which means you may have some room to grow when it comes to the mental side of sports. Athletes with high mental skills scores proactively work to set clear, meaningful goals related to process rather than outcome. They prepare themselves mentally before competitions through aspects such as mindfulness, imagery, and present-moment focus.',
    next_steps: 'To increase your use of mental skills, consider creating a pre-performance routine, engaging in mindfulness activities, and creating some goals for your upcoming season. Take time to reflect on your performances after big training sessions or competitions to identify what went well and what’s worth improving. Use refocusing techniques when things are not going well to help you shift your focus and instead focus on what’s important in the moment. Finally, identify the factors that you have control over and those you don’t have control over so you can direct most of your energy toward the controllables and can let go of the uncontrollables.',
  },
  {
    name: 'mental_skills',
    minPercentile: 40,
    maxPercentile: 80,
    meaning: 'Your Mental Skills score is in the average range when compared to other athletes at your level, which means you may excel in some aspects of the mental side of sports, but may struggle with consistency. Athletes with high scores in this category proactively work to set clear, meaningful goals related to process rather than outcome. They prepare themselves mentally before competitions by practicing mindfulness, imagery, and present-moment focus.',
    next_steps: 'To improve your use of mental skills, start to engage in a pre-performance routine, mindfulness activities, and goal setting activities for your upcoming season. Take time to reflect on your performances after big training sessions or competitions to identify what went well and what’s worth improving. Use refocusing techniques when things are not going well to help you shift your focus and instead focus on what’s important in the moment. Finally, identify the factors that you have control over and those you don’t have control over so you can direct most of your energy toward the controllables and can let go of the uncontrollables.',
  },
  {
    name: 'mental_skills',
    minPercentile: 80,
    maxPercentile: 100,
    meaning: 'Your Mental Skills score is in the above average range in comparison to other  athletes at your level, which means you are likely bringing important sport psychology skills into your day-to-day life. People who score highly in this category proactively work to set clear, meaningful goals related to process rather than outcome. In addition, they prepare themselves mentally before competitions through aspects such as mindfulness, imagery, and present-moment focus.',
    next_steps: 'To maintain your strong use of mental skills, continue to regularly engage in a pre-performance routine, mindfulness activities, and goal setting activities for your upcoming season. Take time to reflect on your performances after big training sessions or competitions to identify what went well and what’s worth improving. Use refocusing techniques when things are not going well to help you shift your focus and instead focus on what’s important in the moment. Finally, identify the factors that you have control over and those you don’t have control over so you can direct most of your energy toward the controllables and can let go of the uncontrollables.',
  },
  {
    name: 'team_support',
    minPercentile: 0,
    maxPercentile: 30,
    meaning: 'Your Team Support score is in the below average range in comparison to other  athletes at your level, which means you may not have felt supported by your teammates or coach(es) lately. Athletes with low scores in this area may feel distant from teammates and coaches and may not feel like they have meaningful connections with coaches or teammates. Those with low scores may also feel as though their value on the team depends on their performance or the outcome of competition.',
    next_steps: 'To generate connection or support on your team, reflect on your role on the team and consider how your role serves as an important piece. Identify your strengths and unique abilities and how you can bring that into training or competition. Get to know members of your team outside of training and competition when given the opportunity. You may also consider speaking with your coach or teammates to share how you’ve been feeling, and explore opportunities for the team to strengthen its relationships with one another.',
  },
  {
    name: 'team_support',
    minPercentile: 40,
    maxPercentile: 70,
    meaning: 'Your Team Support score is in the average range in comparison to other athletes at your level, which means you may feel supported occasionally, but there may be moments where you feel disconnected with your team or coach(es). It may be that you feel support from your team, but not your coach(es) or vice versa. There is also a chance that you feel supported by your team and coach(es) but that support is reliant on how you perform.',
    next_steps: 'To improve your score in this area, reflect on who has supported you in sport and when you feel the most supported. Think about the moments when you felt like your needs were met once you spoke up. Once you have reflected on these things, notice the times you felt as though you were cared about as an athlete and as an individual beyond sport. This can help you become aware of opportunities to connect with others outside of training or competition on a more personal level. Implement what you reflected on by noticing moments where you may distance yourself from others versus opening up to others.',
  },
  {
    name: 'team_support',
    minPercentile: 80,
    maxPercentile: 100,
    meaning: 'Your Team Support score is in the above average range in comparison to other athletes at your level. Athletes with high scores in this category feel like they have strong, meaningful connections with their teammates and coaches. You likely feel that teammates and coaches care about your wellbeing and see you as more than an athlete. Your athletic environment probably encourages open and honest conversations with coaches, and you know your voice is heard and valued. Athletes with high scores in this area also feel valued by teammates and coach(es) regardless of how they performed.',
    next_steps: 'To maintain your score in this area, continue to value the difference and unique voices on your team to maintain open lines of communication. Inclusive voices on a team spark a domino effect, allowing others to feel heard and supported, bringing your team even closer together. Finally, remember to communicate your appreciation to those who have supported you on your journey as an athlete and as a person.',
  },
  {
    name: 'health_habits',
    minPercentile: 0,
    maxPercentile: 30,
    meaning: 'Your Health Habits score is in the below average range in comparison to other athletes at your level, which suggests you may be struggling to prioritize sleep or physical wellness in recent weeks. Athletes with low scores in this area are likely to have inconsistent sleep habits and may not receive the amount of sleep needed to promote health and recovery. They may not be as intentional with nutrition and hydration as they could be, which could lead to difficulties with health or performance. Athletes with low scores in this area are also likely to ignore important warning signs regarding injuries, plateaus, or burnout.',
    next_steps: 'To improve your scores in this area, dial in your sleep patterns and habits so you get enough high quality sleep. Create a sleep routine so it’s easy to wind down at night. Ask yourself whether your current hydration and nutrition regimen supports your wellness and performance goals. Prioritize the recovery process by minimizing physical and mental stress on your recovery days. Finally, be sure to communicate any concerns with coaching staff in order to prevent injuries, plateaus, or burnout.',
  },
  {
    name: 'health_habits',
    minPercentile: 40,
    maxPercentile: 70,
    meaning: 'Your Health Habits score is in the average range in comparison to other athletes at your level. You likely engage in many of the important behaviors needed to promote health and wellness as an athlete, but have room to grow. Athletes who score high in this area prioritize sleep by practicing good sleep habits and getting the amount of sleep needed to promote health and recovery. Athletes with high scores on this scale are also likely to eat a well balanced and nutritious diet, hydrate well, and minimize the consumption of foods and substances that could detract from their health and performance. They are also likely to follow guidelines regarding injury and burnout prevention, which means getting ample amounts of rest and recovery--particularly during intense training periods. You likely practice some of these behaviors, but they may not yet be consistent or considered routine.',
    next_steps: 'To improve your scores in this area, dial in your sleep patterns and habits so you get consistent high quality sleep. Create a sleep routine so it’s easy to wind down at night. Ask yourself whether your current hydration and nutrition regimen supports your wellness and performance goals. Prioritize the recovery process by minimizing physical and mental stress on your recovery days. Finally, be sure to share potential concerns with coaching staff in order to prevent injuries, plateaus, or burnout.',
  },
  {
    name: 'health_habits',
    minPercentile: 80,
    maxPercentile: 100,
    meaning: 'Your Health Habits score is in the above average range in comparison to other athletes at your level, which means you are likely to prioritize your physical health and wellness as an athlete. Athletes who score high in this area prioritize sleep by practicing good sleep habits and getting the amount of sleep needed to promote health and recovery. Athletes with high scores on this scale are also likely to eat a well balanced and nutritious diet, hydrate as needed, and minimize the consumption of foods and substances that could detract from their health and performance. They are also likely to follow guidelines regarding injury and burnout prevention, which means getting ample amounts of rest and recovery--particularly during intense training periods.',
    next_steps: 'To maintain your score in this area, continue to prioritize your sleep by creating a regular bedtime routine, minimizing screen time before bed, minimizing ambient lights and sounds, and sleeping in a dark and cool environment. Make sure your current hydration and nutrition regimen supports your wellness and performance goals. Prioritize the recovery process by minimizing physical and mental stress on your recovery days. Finally, be sure to share potential concerns with coaching staff in order to prevent injuries, plateaus, or burnout.',
  },
  {
    name: 'self_reflection',
    minPercentile: 0,
    maxPercentile: 30,
    meaning: 'Your Self-Reflection score is in the below average range in comparison to other athletes at your level, which suggests you may not be actively using counseling or other sport psychology resources. Athletes with low scores in this area are not likely to reflect on how their personal circumstances, backgrounds, or cultural identities contribute to their role in sport. However, taking time to self-reflect is crucial to growth!',
    next_steps: 'To improve your scores in this area, speak with your coach or a team member to learn about the resources that are available to you. Consider whether there are barriers to seeking care when needed, such as stigma or a lack of information about resources. Additionally, take some time to reflect on how your identities and experiences affect your wellness in and outside of sport.',
  },
  {
    name: 'self_reflection',
    minPercentile: 40,
    maxPercentile: 70,
    meaning: 'Your Self-Reflection score is in the average range in comparison to other athletes at your level, which means you may be open to using some mental health resources on occasion, but may not speak about it openly or use them regularly. You likely have a general understanding of how your cultural identities and past experiences affect you today.',
    next_steps: 'To improve your score in this area, consider taking advantage of counseling, sport psychology, or other resources available to you as an athlete. Take some time to intentionally reflect on your background, your cultural identities, and how they have shaped you as an athlete. Finally, consider opening up to others you trust about your mental and physical health, particularly when feeling stressed or in need of additional support.',
  },
  {
    name: 'self_reflection',
    minPercentile: 80,
    maxPercentile: 100,
    meaning: 'Your Self-Reflection score is in the above average range in comparison to other college athletes, which suggests you regularly engage in self-reflection to understand how experiences affect you as an athlete and as an overall person. Athletes with high scores in this area are likely to use professional resources to support their mental health when needed, and are likely to discuss their experiences openly and honestly with others.',
    next_steps: 'To maintain your score in this area, continue to reflect on how your experiences in and outside of sport affect your wellness. Consider how your cultural identities shape who you are as an athlete. Use the resources that are available when you notice changes in your mental health that could affect your performance and your overall well-being as an athlete.',
  },
]