import { MindBalanceAdultCluster, Language } from "../types";

type PercentileInterpretationEntry = {
  name: MindBalanceAdultCluster;
  language: Language;
  minPercentile: number;
  maxPercentile: number;
  meaning: string;
  developmentalOpportunity?: string;
};

export const percentileInterpretationMindBalanceAdult: PercentileInterpretationEntry[] = [
  // Growth Mindset - English
  {
    name: MindBalanceAdultCluster.ResilientMindset,
    language: Language.English,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'Based on your Growth Mindset score, you are still learning to deal with the pressures of competition, how to embrace challenges, and how to let go of things outside of your control. It can be hard to be consistent with important skills like those. Youth athletes with high scores in this area tend to cope well with the ups and downs in sport. They don\'t worry too much about the performance of others or the outcome of competitions. Instead, they focus on what they can control. They work hard in practice and competition to be the best athlete they can be.',
    developmentalOpportunity: `To improve your scores in this area, consider journaling regularly about your experiences and asking yourself, "What went well? What's worth improving?" after each game or practice. Make sure you celebrate signs of progress throughout the season and set goals you can reach for the season with hard work.`,
  },
  {
    name: MindBalanceAdultCluster.ResilientMindset,
    language: Language.English,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'Your Growth Mindset score is similar to the majority of other youth athletes. This score means you can often deal with pressure, accept challenges, and let go of things outside of your control–but you might not be doing it consistently yet. Youth athletes with scores similar to yours in this area will be okay with the ups and downs in sport. They may sometimes worry about their team\'s performance and whether they are winning or losing. At times, they might be afraid to make mistakes or try new things.',
    developmentalOpportunity: `To work on this area, focus on what is in your control. Set goals that have nothing to do with winning or losing, and celebrate signs of progress throughout your season. Try to find something good in every game or practice. When faced with challenges or uncomfortable situations, remind yourself that failure is a part of success and will help you in the long run. It can help to start a journal where you write down "What went well?" and "What's worth improving?" after each game or practice.`,
  },
  {
    name: MindBalanceAdultCluster.ResilientMindset,
    language: Language.English,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'Your Growth Mindset score is similar to the majority of other youth athletes. This score means you can often deal with pressure, accept challenges, and let go of things outside of your control–but you might not be doing it consistently yet. Youth athletes with scores similar to yours in this area will be okay with the ups and downs in sport. They may sometimes worry about their team\'s performance and whether they are winning or losing. At times, they might be afraid to make mistakes or try new things.',
    developmentalOpportunity: `To work on this area, focus on what is in your control. Set goals that have nothing to do with winning or losing, and celebrate signs of progress throughout your season. Try to find something good in every game or practice. When faced with challenges or uncomfortable situations, remind yourself that failure is a part of success and will help you in the long run. It can help to start a journal where you write down "What went well?" and "What's worth improving?" after each game or practice.`,
  },
  {
    name: MindBalanceAdultCluster.ResilientMindset,
    language: Language.English,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'Your Growth Mindset score is similar to the majority of other youth athletes. This score means you can often deal with pressure, accept challenges, and let go of things outside of your control–but you might not be doing it consistently yet. Youth athletes with scores similar to yours in this area will be okay with the ups and downs in sport. They may sometimes worry about their team\'s performance and whether they are winning or losing. At times, they might be afraid to make mistakes or try new things.',
    developmentalOpportunity: `To work on this area, focus on what is in your control. Set goals that have nothing to do with winning or losing, and celebrate signs of progress throughout your season. Try to find something good in every game or practice. When faced with challenges or uncomfortable situations, remind yourself that failure is a part of success and will help you in the long run. It can help to start a journal where you write down "What went well?" and "What's worth improving?" after each game or practice.`,
  },
  {
    name: MindBalanceAdultCluster.ResilientMindset,
    language: Language.English,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Your Growth Mindset score is in the above average range in comparison to other youth athletes. This score shows you are learning important skills in sport that will make you a better athlete in the future. These skills include dealing with pressure, accepting challenges, and letting go of things outside of your control. Youth athletes with high scores in this area are also likely to be okay with the ups and downs in sport. They\'re not likely to worry about the performance of others or winning/losing. Instead, they focus on what they control and work hard in practice and competition to be the best athlete they can be.',
    developmentalOpportunity: `To maintain your scores in this area, consider journaling regularly about your experiences and asking yourself, "What went well? What's worth improving?" after each game or practice. Make sure you celebrate signs of progress throughout the season and set goals you can reach for the season with hard work.`,
  },
  // Self-Confidence - English
  {
    name: MindBalanceAdultCluster.MentalSkills,
    language: Language.English,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'Your Self-Confidence score is lower compared to other youth athletes. Self-confidence is your core beliefs about yourself. Your score suggests that you are still strengthening your views and beliefs about yourself. Those who score higher in this category, use healthy coping skills. You are still in the process of learning them and applying them to your life, and that is okay!',
    developmentalOpportunity: `To improve your confidence, try to start asking more questions in practice. Let your coach know how you're doing and how you're feeling. It's okay if you don't feel comfortable right away—try to start with small questions and small pieces of information, and then ask for help more often as you get more comfortable. Another thing you can do to help you think positively and improve your confidence is to write down 3 good things you did at each practice or game. If you don't know, ask your coach to help! Finally, remember to focus on being the best athlete you can be regardless of what other people think, say, or do.`,
  },
  {
    name: MindBalanceAdultCluster.MentalSkills,
    language: Language.English,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'Your Self-Confidence score was similar to other youth athletes. Self-confidence is your beliefs about yourself and your abilities. This score shows that you may at times feel like you are good enough just the way you are, and other times you may feel like you are not good enough. You may know some coping skills and use them at times, but might not use them as often as you could. Athletes with scores like yours can ask questions and ask for help when needed, but may not do it as often as they could. They can deal with pressure most of the time, but may struggle with this once in a while.',
    developmentalOpportunity: `To improve your confidence, try to start asking more questions in practice. Let your coach know how you're doing and how you're feeling. It will also help to think positive by writing down 3 good things you did at each practice or game. If you don't know, ask your coach to help! Finally, remember to focus on being the best athlete you can be regardless of what other people think, say, or do.`,
  },
  {
    name: MindBalanceAdultCluster.MentalSkills,
    language: Language.English,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'Your Self-Confidence score was similar to other youth athletes. Self-confidence is your beliefs about yourself and your abilities. This score shows that you may at times feel like you are good enough just the way you are, and other times you may feel like you are not good enough. You may know some coping skills and use them at times, but might not use them as often as you could. Athletes with scores like yours can ask questions and ask for help when needed, but may not do it as often as they could. They can deal with pressure most of the time, but may struggle with this once in a while.',
    developmentalOpportunity: `To improve your confidence, try to start asking more questions in practice. Let your coach know how you're doing and how you're feeling. It will also help to think positive by writing down 3 good things you did at each practice or game. If you don't know, ask your coach to help! Finally, remember to focus on being the best athlete you can be regardless of what other people think, say, or do.`,
  },
  {
    name: MindBalanceAdultCluster.MentalSkills,
    language: Language.English,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'Your Self-Confidence score was similar to other youth athletes. Self-confidence is your beliefs about yourself and your abilities. This score shows that you may at times feel like you are good enough just the way you are, and other times you may feel like you are not good enough. You may know some coping skills and use them at times, but might not use them as often as you could. Athletes with scores like yours can ask questions and ask for help when needed, but may not do it as often as they could. They can deal with pressure most of the time, but may struggle with this once in a while.',
    developmentalOpportunity: `To improve your confidence, try to start asking more questions in practice. Let your coach know how you're doing and how you're feeling. It will also help to think positive by writing down 3 good things you did at each practice or game. If you don't know, ask your coach to help! Finally, remember to focus on being the best athlete you can be regardless of what other people think, say, or do.`,
  },
  {
    name: MindBalanceAdultCluster.MentalSkills,
    language: Language.English,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Your Self-Confidence score was higher than other youth athletes. Self-confidence is your beliefs about yourself and your abilities. This score means you probably feel like you are good enough just the way you are. You probably keep a positive mindset and focus. You also probably know when to use healthy coping skills. Athletes with high scores in this area almost always focus on what is important, on and off the field.',
    developmentalOpportunity: `You can keep your self-confidence high by asking questions to coaches, teammates, and parents to improve your view of yourself and your abilities. Finally, remember to focus on being the best athlete you can be regardless of what other people think, say, or do.`,
  },
  // Team Culture - English
  {
    name: MindBalanceAdultCluster.TeamSupport,
    language: Language.English,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'Your Team Culture score tells us you feel like your teammates or community may not be supporting you enough on and off the field. You may feel distant from your team at times. Those with above average scores feel as though their value does not depend on whether they win or lose.',
    developmentalOpportunity: `To work on this area, reflect on your role on the team and consider how your role serves as an important piece. Identify your strengths and unique abilities and how you can bring that into training or competition. Get to know members of your team outside of training and competition when given the opportunity. You may also consider speaking with your coach or teammates to share how you've been feeling, and explore opportunities for the team to strengthen its relationships with one another.`,
  },
  {
    name: MindBalanceAdultCluster.TeamSupport,
    language: Language.English,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'Your Team Culture score is in the average range in comparison to other youth athletes, which means you may feel supported at times, but there may be moments where you feel disconnected from your team or community. It may be that you feel supported by your team, but not your family, or vice versa. There is also a chance that you feel supported by your team and family but it depends on how you perform.',
    developmentalOpportunity: `To improve your score in this area, think about who you feel supported by, when you feel the most supported, and when you feel like your needs were met once you spoke up. Once you have thought about these things, notice the times you felt cared about as an athlete and person. This can help you become aware of opportunities to connect with others outside of training or competition on a more personal level. Take what you thought about by noticing moments where you may try to keep yourself far from others versus opening up to others.`,
  },
  {
    name: MindBalanceAdultCluster.TeamSupport,
    language: Language.English,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'Your Team Culture score is in the average range in comparison to other youth athletes, which means you may feel supported at times, but there may be moments where you feel disconnected from your team or community. It may be that you feel supported by your team, but not your family, or vice versa. There is also a chance that you feel supported by your team and family but it depends on how you perform.',
    developmentalOpportunity: `To improve your score in this area, think about who you feel supported by, when you feel the most supported, and when you feel like your needs were met once you spoke up. Once you have thought about these things, notice the times you felt cared about as an athlete and person. This can help you become aware of opportunities to connect with others outside of training or competition on a more personal level. Take what you thought about by noticing moments where you may try to keep yourself far from others versus opening up to others.`,
  },
  {
    name: MindBalanceAdultCluster.TeamSupport,
    language: Language.English,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'Your Team Culture score is in the average range in comparison to other youth athletes, which means you may feel supported at times, but there may be moments where you feel disconnected from your team or community. It may be that you feel supported by your team, but not your family, or vice versa. There is also a chance that you feel supported by your team and family but it depends on how you perform.',
    developmentalOpportunity: `To improve your score in this area, think about who you feel supported by, when you feel the most supported, and when you feel like your needs were met once you spoke up. Once you have thought about these things, notice the times you felt cared about as an athlete and person. This can help you become aware of opportunities to connect with others outside of training or competition on a more personal level. Take what you thought about by noticing moments where you may try to keep yourself far from others versus opening up to others.`,
  },
  {
    name: MindBalanceAdultCluster.TeamSupport,
    language: Language.English,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Your Team Culture score is higher than most youth athletes. Youth athletes who score highly in this category tend to have strong, meaningful relationships with their team and community. You likely feel that people care about your wellbeing and see you as more than an athlete. You are likely to be in an environment that has open and honest conversations with others, and feel heard and valued for who you are. Youth athletes who score high in this category also feel they are valued by others no matter how they perform.',
    developmentalOpportunity: `To keep your score high in this area, continue to value those on your team and keep communicating with coaches, friends, and family. Being a kind voice on your team can be like a domino effect, allowing your teammates to feel they are being listened to and supported which can bring your team closer together. In addition, you should try to talk about your appreciation to those who have supported you during your time as an athlete and as a person.`,
  },
  // Health Behaviors - English
  {
    name: MindBalanceAdultCluster.HealthHabits,
    language: Language.English,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'Your Health Behaviors score is in the below average range compared to other youth athletes, which means you are trying to balance sport and other areas of your life. Being dedicated to your sport can be time consuming which is why it is important to not let other important areas slip away, such as your sleep and nutrition. Youth athletes with high scores in this area feel a good balance between life and sport, limit their social media use, have good sleep habits, and eat well.',
    developmentalOpportunity: `To improve your scores in this area, ask yourself what areas need the most improvement when it comes to finding the right balance between sports, friends, family, and other hobbies. Consider dialing in your sleep routine by putting your phone away, going to bed and waking up at the same time every day, and eating good quality meals. You can also be intentional with recovery days to make sure you're taking time outside of sport to rest.`,
  },
  {
    name: MindBalanceAdultCluster.HealthHabits,
    language: Language.English,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'Your Health Behaviors score is in the average range in comparison to other youth athletes, which means you are likely doing some things that are important to physical health and mental health outside of sport, but have some areas to improve on. Youth athletes with high scores in this area feel a good balance between life and sport, limit their social media use, have good sleep habits, and eat well.',
    developmentalOpportunity: `To improve scores in this area, ask yourself what areas need the most improvement when it comes to finding the right balance between sports, friends, family, and other hobbies. Consider changing your sleep routine by putting your phone away, going to bed and waking up at the same time every day, and eating good quality meals. You can also choose to have recovery days to make sure you're taking time outside of sport to rest.`,
  },
  {
    name: MindBalanceAdultCluster.HealthHabits,
    language: Language.English,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'Your Health Behaviors score is in the average range in comparison to other youth athletes, which means you are likely doing some things that are important to physical health and mental health outside of sport, but have some areas to improve on. Youth athletes with high scores in this area feel a good balance between life and sport, limit their social media use, have good sleep habits, and eat well.',
    developmentalOpportunity: `To improve scores in this area, ask yourself what areas need the most improvement when it comes to finding the right balance between sports, friends, family, and other hobbies. Consider changing your sleep routine by putting your phone away, going to bed and waking up at the same time every day, and eating good quality meals. You can also choose to have recovery days to make sure you're taking time outside of sport to rest.`,
  },
  {
    name: MindBalanceAdultCluster.HealthHabits,
    language: Language.English,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'Your Health Behaviors score is in the average range in comparison to other youth athletes, which means you are likely doing some things that are important to physical health and mental health outside of sport, but have some areas to improve on. Youth athletes with high scores in this area feel a good balance between life and sport, limit their social media use, have good sleep habits, and eat well.',
    developmentalOpportunity: `To improve scores in this area, ask yourself what areas need the most improvement when it comes to finding the right balance between sports, friends, family, and other hobbies. Consider changing your sleep routine by putting your phone away, going to bed and waking up at the same time every day, and eating good quality meals. You can also choose to have recovery days to make sure you're taking time outside of sport to rest.`,
  },
  {
    name: MindBalanceAdultCluster.HealthHabits,
    language: Language.English,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Your Health Behaviors score is in the above average range in comparison to other youth athletes, which means you are likely doing things that are important to physical health and mental health outside of sport. Youth athletes with high scores in this area feel a good balance between life and sport, limit social media use, have good sleep habits, and eat well.',
    developmentalOpportunity: `To maintain scores in this area, ask yourself what areas you can continue to improve on when it comes to finding the right balance between sports, friends, family, and other hobbies. Keep up with your sleep routine even more than you've already done. You can also choose to have recovery days to make sure you're taking time outside of sport to rest.`,
  },
  // Growth Mindset - Spanish
  {
    name: MindBalanceAdultCluster.ResilientMindset,
    language: Language.Spanish,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'Según tu puntuación de Mentalidad de Crecimiento, todavía estás aprendiendo a lidiar con las presiones de la competencia, cómo abrazar los desafíos y cómo dejar ir las cosas fuera de tu control. Puede ser difícil ser consistente con habilidades importantes como esas. Los atletas jóvenes con puntuaciones altas en esta área tienden a lidiar bien con los altibajos en el deporte. No se preocupan demasiado por el rendimiento de otros o el resultado de las competencias. En cambio, se enfocan en lo que pueden controlar. Trabajan duro en la práctica y la competencia para ser el mejor atleta que pueden ser.',
    developmentalOpportunity: `Para mejorar tus puntuaciones en esta área, considera llevar un diario regularmente sobre tus experiencias y preguntarte: "¿Qué salió bien? ¿Qué vale la pena mejorar?" después de cada juego o práctica. Asegúrate de celebrar las señales de progreso a lo largo de la temporada y establece metas que puedas alcanzar para la temporada con trabajo duro.`,
  },
  {
    name: MindBalanceAdultCluster.ResilientMindset,
    language: Language.Spanish,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'Tu puntuación de Mentalidad de Crecimiento es similar a la mayoría de otros atletas jóvenes. Esta puntuación significa que a menudo puedes lidiar con la presión, aceptar desafíos y dejar ir las cosas fuera de tu control, pero es posible que aún no lo estés haciendo de manera consistente. Los atletas jóvenes con puntuaciones similares a las tuyas en esta área estarán bien con los altibajos en el deporte. A veces pueden preocuparse por el rendimiento de su equipo y si están ganando o perdiendo. A veces, pueden tener miedo de cometer errores o probar cosas nuevas.',
    developmentalOpportunity: `Para trabajar en esta área, enfócate en lo que está bajo tu control. Establece metas que no tengan nada que ver con ganar o perder, y celebra las señales de progreso a lo largo de tu temporada. Trata de encontrar algo bueno en cada juego o práctica. Cuando te enfrentes a desafíos o situaciones incómodas, recuerda que el fracaso es parte del éxito y te ayudará a largo plazo. Puede ayudar comenzar un diario donde escribas "¿Qué salió bien?" y "¿Qué vale la pena mejorar?" después de cada juego o práctica.`,
  },
  {
    name: MindBalanceAdultCluster.ResilientMindset,
    language: Language.Spanish,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'Tu puntuación de Mentalidad de Crecimiento es similar a la mayoría de otros atletas jóvenes. Esta puntuación significa que a menudo puedes lidiar con la presión, aceptar desafíos y dejar ir las cosas fuera de tu control, pero es posible que aún no lo estés haciendo de manera consistente. Los atletas jóvenes con puntuaciones similares a las tuyas en esta área estarán bien con los altibajos en el deporte. A veces pueden preocuparse por el rendimiento de su equipo y si están ganando o perdiendo. A veces, pueden tener miedo de cometer errores o probar cosas nuevas.',
    developmentalOpportunity: `Para trabajar en esta área, enfócate en lo que está bajo tu control. Establece metas que no tengan nada que ver con ganar o perder, y celebra las señales de progreso a lo largo de tu temporada. Trata de encontrar algo bueno en cada juego o práctica. Cuando te enfrentes a desafíos o situaciones incómodas, recuerda que el fracaso es parte del éxito y te ayudará a largo plazo. Puede ayudar comenzar un diario donde escribas "¿Qué salió bien?" y "¿Qué vale la pena mejorar?" después de cada juego o práctica.`,
  },
  {
    name: MindBalanceAdultCluster.ResilientMindset,
    language: Language.Spanish,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'Tu puntuación de Mentalidad de Crecimiento es similar a la mayoría de otros atletas jóvenes. Esta puntuación significa que a menudo puedes lidiar con la presión, aceptar desafíos y dejar ir las cosas fuera de tu control, pero es posible que aún no lo estés haciendo de manera consistente. Los atletas jóvenes con puntuaciones similares a las tuyas en esta área estarán bien con los altibajos en el deporte. A veces pueden preocuparse por el rendimiento de su equipo y si están ganando o perdiendo. A veces, pueden tener miedo de cometer errores o probar cosas nuevas.',
    developmentalOpportunity: `Para trabajar en esta área, enfócate en lo que está bajo tu control. Establece metas que no tengan nada que ver con ganar o perder, y celebra las señales de progreso a lo largo de tu temporada. Trata de encontrar algo bueno en cada juego o práctica. Cuando te enfrentes a desafíos o situaciones incómodas, recuerda que el fracaso es parte del éxito y te ayudará a largo plazo. Puede ayudar comenzar un diario donde escribas "¿Qué salió bien?" y "¿Qué vale la pena mejorar?" después de cada juego o práctica.`,
  },
  {
    name: MindBalanceAdultCluster.ResilientMindset,
    language: Language.Spanish,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Tu puntuación de Mentalidad de Crecimiento está en el rango por encima del promedio en comparación con otros atletas jóvenes. Esta puntuación muestra que estás aprendiendo habilidades importantes en el deporte que te harán un mejor atleta en el futuro. Estas habilidades incluyen lidiar con la presión, aceptar desafíos y dejar ir las cosas fuera de tu control. Los atletas jóvenes con puntuaciones altas en esta área también es probable que estén bien con los altibajos en el deporte. Es poco probable que se preocupen por el rendimiento de otros o ganar/perder. En cambio, se enfocan en lo que controlan y trabajan duro en la práctica y la competencia para ser el mejor atleta que pueden ser.',
    developmentalOpportunity: `Para mantener tus puntuaciones en esta área, considera llevar un diario regularmente sobre tus experiencias y preguntarte: "¿Qué salió bien? ¿Qué vale la pena mejorar?" después de cada juego o práctica. Asegúrate de celebrar las señales de progreso a lo largo de la temporada y establece metas que puedas alcanzar para la temporada con trabajo duro.`,
  },
  // Self-Confidence - Spanish
  {
    name: MindBalanceAdultCluster.MentalSkills,
    language: Language.Spanish,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'Tu puntuación de Autoconfianza es más baja en comparación con otros atletas jóvenes. La autoconfianza son tus creencias fundamentales sobre ti mismo. Tu puntuación sugiere que todavía estás fortaleciendo tus puntos de vista y creencias sobre ti mismo. Aquellos que obtienen puntuaciones más altas en esta categoría usan habilidades de afrontamiento saludables. Todavía estás en el proceso de aprenderlas y aplicarlas a tu vida, ¡y eso está bien!',
    developmentalOpportunity: `Para mejorar tu confianza, trata de comenzar a hacer más preguntas en la práctica. Hazle saber a tu entrenador cómo te está yendo y cómo te sientes. Está bien si no te sientes cómodo de inmediato: trata de comenzar con preguntas pequeñas y pequeñas piezas de información, y luego pide ayuda con más frecuencia a medida que te sientas más cómodo. Otra cosa que puedes hacer para ayudarte a pensar positivamente y mejorar tu confianza es escribir 3 cosas buenas que hiciste en cada práctica o juego. Si no lo sabes, ¡pídele ayuda a tu entrenador! Finalmente, recuerda enfocarte en ser el mejor atleta que puedas ser sin importar lo que otras personas piensen, digan o hagan.`,
  },
  {
    name: MindBalanceAdultCluster.MentalSkills,
    language: Language.Spanish,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'Tu puntuación de Autoconfianza fue similar a la de otros atletas jóvenes. La autoconfianza son tus creencias sobre ti mismo y tus habilidades. Esta puntuación muestra que a veces puedes sentir que eres lo suficientemente bueno tal como eres, y otras veces puedes sentir que no eres lo suficientemente bueno. Puedes conocer algunas habilidades de afrontamiento y usarlas a veces, pero es posible que no las uses tan a menudo como podrías. Los atletas con puntuaciones como las tuyas pueden hacer preguntas y pedir ayuda cuando sea necesario, pero es posible que no lo hagan tan a menudo como podrían. Pueden lidiar con la presión la mayor parte del tiempo, pero pueden tener dificultades con esto de vez en cuando.',
    developmentalOpportunity: `Para mejorar tu confianza, trata de comenzar a hacer más preguntas en la práctica. Hazle saber a tu entrenador cómo te está yendo y cómo te sientes. También ayudará pensar positivo escribiendo 3 cosas buenas que hiciste en cada práctica o juego. Si no lo sabes, ¡pídele ayuda a tu entrenador! Finalmente, recuerda enfocarte en ser el mejor atleta que puedas ser sin importar lo que otras personas piensen, digan o hagan.`,
  },
  {
    name: MindBalanceAdultCluster.MentalSkills,
    language: Language.Spanish,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'Tu puntuación de Autoconfianza fue similar a la de otros atletas jóvenes. La autoconfianza son tus creencias sobre ti mismo y tus habilidades. Esta puntuación muestra que a veces puedes sentir que eres lo suficientemente bueno tal como eres, y otras veces puedes sentir que no eres lo suficientemente bueno. Puedes conocer algunas habilidades de afrontamiento y usarlas a veces, pero es posible que no las uses tan a menudo como podrías. Los atletas con puntuaciones como las tuyas pueden hacer preguntas y pedir ayuda cuando sea necesario, pero es posible que no lo hagan tan a menudo como podrían. Pueden lidiar con la presión la mayor parte del tiempo, pero pueden tener dificultades con esto de vez en cuando.',
    developmentalOpportunity: `Para mejorar tu confianza, trata de comenzar a hacer más preguntas en la práctica. Hazle saber a tu entrenador cómo te está yendo y cómo te sientes. También ayudará pensar positivo escribiendo 3 cosas buenas que hiciste en cada práctica o juego. Si no lo sabes, ¡pídele ayuda a tu entrenador! Finalmente, recuerda enfocarte en ser el mejor atleta que puedas ser sin importar lo que otras personas piensen, digan o hagan.`,
  },
  {
    name: MindBalanceAdultCluster.MentalSkills,
    language: Language.Spanish,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'Tu puntuación de Autoconfianza fue similar a la de otros atletas jóvenes. La autoconfianza son tus creencias sobre ti mismo y tus habilidades. Esta puntuación muestra que a veces puedes sentir que eres lo suficientemente bueno tal como eres, y otras veces puedes sentir que no eres lo suficientemente bueno. Puedes conocer algunas habilidades de afrontamiento y usarlas a veces, pero es posible que no las uses tan a menudo como podrías. Los atletas con puntuaciones como las tuyas pueden hacer preguntas y pedir ayuda cuando sea necesario, pero es posible que no lo hagan tan a menudo como podrían. Pueden lidiar con la presión la mayor parte del tiempo, pero pueden tener dificultades con esto de vez en cuando.',
    developmentalOpportunity: `Para mejorar tu confianza, trata de comenzar a hacer más preguntas en la práctica. Hazle saber a tu entrenador cómo te está yendo y cómo te sientes. También ayudará pensar positivo escribiendo 3 cosas buenas que hiciste en cada práctica o juego. Si no lo sabes, ¡pídele ayuda a tu entrenador! Finalmente, recuerda enfocarte en ser el mejor atleta que puedas ser sin importar lo que otras personas piensen, digan o hagan.`,
  },
  {
    name: MindBalanceAdultCluster.MentalSkills,
    language: Language.Spanish,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Tu puntuación de Autoconfianza fue más alta que la de otros atletas jóvenes. La autoconfianza son tus creencias sobre ti mismo y tus habilidades. Esta puntuación significa que probablemente sientes que eres lo suficientemente bueno tal como eres. Probablemente mantienes una mentalidad y enfoque positivos. También probablemente sabes cuándo usar habilidades de afrontamiento saludables. Los atletas con puntuaciones altas en esta área casi siempre se enfocan en lo que es importante, dentro y fuera del campo.',
    developmentalOpportunity: `Puedes mantener tu autoconfianza alta haciendo preguntas a entrenadores, compañeros de equipo y padres para mejorar tu visión de ti mismo y tus habilidades. Finalmente, recuerda enfocarte en ser el mejor atleta que puedas ser sin importar lo que otras personas piensen, digan o hagan.`,
  },
  // Team Culture - Spanish
  {
    name: MindBalanceAdultCluster.TeamSupport,
    language: Language.Spanish,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'Tu puntuación de Cultura de Equipo nos dice que sientes que tus compañeros de equipo o la comunidad pueden no estar apoyándote lo suficiente dentro y fuera del campo. Puedes sentirte distante de tu equipo a veces. Aquellos con puntuaciones por encima del promedio sienten que su valor no depende de si ganan o pierden.',
    developmentalOpportunity: `Para trabajar en esta área, reflexiona sobre tu papel en el equipo y considera cómo tu papel sirve como una pieza importante. Identifica tus fortalezas y habilidades únicas y cómo puedes llevarlas al entrenamiento o la competencia. Conoce a los miembros de tu equipo fuera del entrenamiento y la competencia cuando tengas la oportunidad. También puedes considerar hablar con tu entrenador o compañeros de equipo para compartir cómo te has estado sintiendo, y explorar oportunidades para que el equipo fortalezca sus relaciones entre sí.`,
  },
  {
    name: MindBalanceAdultCluster.TeamSupport,
    language: Language.Spanish,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'Tu puntuación de Cultura de Equipo está en el rango promedio en comparación con otros atletas jóvenes, lo que significa que puedes sentirte apoyado a veces, pero puede haber momentos en los que te sientas desconectado de tu equipo o comunidad. Puede ser que te sientas apoyado por tu equipo, pero no por tu familia, o viceversa. También existe la posibilidad de que te sientas apoyado por tu equipo y tu familia, pero depende de cómo te desempeñes.',
    developmentalOpportunity: `Para mejorar tu puntuación en esta área, piensa en quién te sientes apoyado, cuándo te sientes más apoyado y cuándo sientes que se cumplieron tus necesidades una vez que hablaste. Una vez que hayas pensado en estas cosas, nota las veces que te sentiste cuidado como atleta y persona. Esto puede ayudarte a ser consciente de las oportunidades para conectarte con otros fuera del entrenamiento o la competencia en un nivel más personal. Toma lo que pensaste notando momentos en los que puedes intentar mantenerte lejos de otros versus abrirte a otros.`,
  },
  {
    name: MindBalanceAdultCluster.TeamSupport,
    language: Language.Spanish,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'Tu puntuación de Cultura de Equipo está en el rango promedio en comparación con otros atletas jóvenes, lo que significa que puedes sentirte apoyado a veces, pero puede haber momentos en los que te sientas desconectado de tu equipo o comunidad. Puede ser que te sientas apoyado por tu equipo, pero no por tu familia, o viceversa. También existe la posibilidad de que te sientas apoyado por tu equipo y tu familia, pero depende de cómo te desempeñes.',
    developmentalOpportunity: `Para mejorar tu puntuación en esta área, piensa en quién te sientes apoyado, cuándo te sientes más apoyado y cuándo sientes que se cumplieron tus necesidades una vez que hablaste. Una vez que hayas pensado en estas cosas, nota las veces que te sentiste cuidado como atleta y persona. Esto puede ayudarte a ser consciente de las oportunidades para conectarte con otros fuera del entrenamiento o la competencia en un nivel más personal. Toma lo que pensaste notando momentos en los que puedes intentar mantenerte lejos de otros versus abrirte a otros.`,
  },
  {
    name: MindBalanceAdultCluster.TeamSupport,
    language: Language.Spanish,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'Tu puntuación de Cultura de Equipo está en el rango promedio en comparación con otros atletas jóvenes, lo que significa que puedes sentirte apoyado a veces, pero puede haber momentos en los que te sientas desconectado de tu equipo o comunidad. Puede ser que te sientas apoyado por tu equipo, pero no por tu familia, o viceversa. También existe la posibilidad de que te sientas apoyado por tu equipo y tu familia, pero depende de cómo te desempeñes.',
    developmentalOpportunity: `Para mejorar tu puntuación en esta área, piensa en quién te sientes apoyado, cuándo te sientes más apoyado y cuándo sientes que se cumplieron tus necesidades una vez que hablaste. Una vez que hayas pensado en estas cosas, nota las veces que te sentiste cuidado como atleta y persona. Esto puede ayudarte a ser consciente de las oportunidades para conectarte con otros fuera del entrenamiento o la competencia en un nivel más personal. Toma lo que pensaste notando momentos en los que puedes intentar mantenerte lejos de otros versus abrirte a otros.`,
  },
  {
    name: MindBalanceAdultCluster.TeamSupport,
    language: Language.Spanish,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Tu puntuación de Cultura de Equipo es más alta que la mayoría de los atletas jóvenes. Los atletas jóvenes que obtienen puntuaciones altas en esta categoría tienden a tener relaciones fuertes y significativas con su equipo y comunidad. Es probable que sientas que a las personas les importa tu bienestar y te ven como más que un atleta. Es probable que estés en un entorno que tiene conversaciones abiertas y honestas con otros, y te sientes escuchado y valorado por quién eres. Los atletas jóvenes que obtienen puntuaciones altas en esta categoría también sienten que son valorados por otros sin importar cómo se desempeñen.',
    developmentalOpportunity: `Para mantener tu puntuación alta en esta área, continúa valorando a los de tu equipo y mantén la comunicación con entrenadores, amigos y familia. Ser una voz amable en tu equipo puede ser como un efecto dominó, permitiendo que tus compañeros de equipo sientan que están siendo escuchados y apoyados, lo que puede acercar más a tu equipo. Además, debes intentar hablar sobre tu aprecio a aquellos que te han apoyado durante tu tiempo como atleta y como persona.`,
  },
  // Health Behaviors - Spanish
  {
    name: MindBalanceAdultCluster.HealthHabits,
    language: Language.Spanish,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'Tu puntuación de Comportamientos Saludables está en el rango por debajo del promedio en comparación con otros atletas jóvenes, lo que significa que estás tratando de equilibrar el deporte y otras áreas de tu vida. Estar dedicado a tu deporte puede llevar mucho tiempo, por eso es importante no dejar que otras áreas importantes se deslicen, como tu sueño y nutrición. Los atletas jóvenes con puntuaciones altas en esta área sienten un buen equilibrio entre la vida y el deporte, limitan su uso de redes sociales, tienen buenos hábitos de sueño y comen bien.',
    developmentalOpportunity: `Para mejorar tus puntuaciones en esta área, pregúntate qué áreas necesitan más mejora cuando se trata de encontrar el equilibrio adecuado entre deportes, amigos, familia y otros pasatiempos. Considera ajustar tu rutina de sueño guardando tu teléfono, yendo a la cama y despertándote a la misma hora todos los días, y comiendo comidas de buena calidad. También puedes ser intencional con los días de recuperación para asegurarte de que estás tomando tiempo fuera del deporte para descansar.`,
  },
  {
    name: MindBalanceAdultCluster.HealthHabits,
    language: Language.Spanish,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'Tu puntuación de Comportamientos Saludables está en el rango promedio en comparación con otros atletas jóvenes, lo que significa que es probable que estés haciendo algunas cosas que son importantes para la salud física y mental fuera del deporte, pero tienes algunas áreas en las que mejorar. Los atletas jóvenes con puntuaciones altas en esta área sienten un buen equilibrio entre la vida y el deporte, limitan su uso de redes sociales, tienen buenos hábitos de sueño y comen bien.',
    developmentalOpportunity: `Para mejorar las puntuaciones en esta área, pregúntate qué áreas necesitan más mejora cuando se trata de encontrar el equilibrio adecuado entre deportes, amigos, familia y otros pasatiempos. Considera cambiar tu rutina de sueño guardando tu teléfono, yendo a la cama y despertándote a la misma hora todos los días, y comiendo comidas de buena calidad. También puedes elegir tener días de recuperación para asegurarte de que estás tomando tiempo fuera del deporte para descansar.`,
  },
  {
    name: MindBalanceAdultCluster.HealthHabits,
    language: Language.Spanish,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'Tu puntuación de Comportamientos Saludables está en el rango promedio en comparación con otros atletas jóvenes, lo que significa que es probable que estés haciendo algunas cosas que son importantes para la salud física y mental fuera del deporte, pero tienes algunas áreas en las que mejorar. Los atletas jóvenes con puntuaciones altas en esta área sienten un buen equilibrio entre la vida y el deporte, limitan su uso de redes sociales, tienen buenos hábitos de sueño y comen bien.',
    developmentalOpportunity: `Para mejorar las puntuaciones en esta área, pregúntate qué áreas necesitan más mejora cuando se trata de encontrar el equilibrio adecuado entre deportes, amigos, familia y otros pasatiempos. Considera cambiar tu rutina de sueño guardando tu teléfono, yendo a la cama y despertándote a la misma hora todos los días, y comiendo comidas de buena calidad. También puedes elegir tener días de recuperación para asegurarte de que estás tomando tiempo fuera del deporte para descansar.`,
  },
  {
    name: MindBalanceAdultCluster.HealthHabits,
    language: Language.Spanish,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'Tu puntuación de Comportamientos Saludables está en el rango promedio en comparación con otros atletas jóvenes, lo que significa que es probable que estés haciendo algunas cosas que son importantes para la salud física y mental fuera del deporte, pero tienes algunas áreas en las que mejorar. Los atletas jóvenes con puntuaciones altas en esta área sienten un buen equilibrio entre la vida y el deporte, limitan su uso de redes sociales, tienen buenos hábitos de sueño y comen bien.',
    developmentalOpportunity: `Para mejorar las puntuaciones en esta área, pregúntate qué áreas necesitan más mejora cuando se trata de encontrar el equilibrio adecuado entre deportes, amigos, familia y otros pasatiempos. Considera cambiar tu rutina de sueño guardando tu teléfono, yendo a la cama y despertándote a la misma hora todos los días, y comiendo comidas de buena calidad. También puedes elegir tener días de recuperación para asegurarte de que estás tomando tiempo fuera del deporte para descansar.`,
  },
  {
    name: MindBalanceAdultCluster.HealthHabits,
    language: Language.Spanish,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Tu puntuación de Comportamientos Saludables está en el rango por encima del promedio en comparación con otros atletas jóvenes, lo que significa que es probable que estés haciendo cosas que son importantes para la salud física y mental fuera del deporte. Los atletas jóvenes con puntuaciones altas en esta área sienten un buen equilibrio entre la vida y el deporte, limitan el uso de redes sociales, tienen buenos hábitos de sueño y comen bien.',
    developmentalOpportunity: `Para mantener las puntuaciones en esta área, pregúntate qué áreas puedes seguir mejorando cuando se trata de encontrar el equilibrio adecuado entre deportes, amigos, familia y otros pasatiempos. Mantén tu rutina de sueño incluso más de lo que ya has hecho. También puedes elegir tener días de recuperación para asegurarte de que estás tomando tiempo fuera del deporte para descansar.`,
  },
];

