import { MindBalanceAdultCluster, Language } from "../types";

type PercentileInterpretationEntry = {
  name: MindBalanceAdultCluster;
  language: Language;
  minPercentile: number;
  maxPercentile: number;
  meaning: string;
  developmentalOpportunity?: string;
};

export const percentileInterpretationMindBalanceAdult: PercentileInterpretationEntry[] = [
  // Resilient Mindset - English
  {
    name: MindBalanceAdultCluster.ResilientMindset,
    language: Language.English,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'In your sporting experience, you may seek perfection which may cause you to feel held back by negative thoughts that arise while training and competing. You may also set high expectations for yourself and feel pressure to succeed. Athletes with scores in this range often feel their self-worth is based on their performance or abilities. This pattern of thinking can lead to fear of failure, self-criticism, and anxiety when pushed outside of your comfort zone.',
    developmentalOpportunity: `To improve your Resilient Mindset, respond to your mistakes with curiosity. Ask yourself what caused you to not be successful and what can you learn from this mistake. Frame imperfections as learning opportunities. By becoming more aware of your inner dialogue, you can damper your inner critic and rebuild an inner dialogue that supports your resiliency.`,
  },
  {
    name: MindBalanceAdultCluster.ResilientMindset,
    language: Language.English,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'You may support yourself in general, but would benefit from giving yourself a break when you don\'t meet your expectations. During challenging times, negative thoughts may become intrusive which can lead to self-criticism, allowing little margin for error. Athletes with high scores in this area consistently believe in themselves and can quickly recover from setbacks. They understand their self-worth is not defined by their performance, but by their ability to continuously push forward and bounce back. You may have these views occasionally, but may waiver in certain situations.',
    developmentalOpportunity: `To improve this area, notice your inner critic when it appears and ask yourself whether such thoughts help you be the athlete you want to be. If you notice your inner critic taking over, ask yourself if these thoughts are helpful or unhelpful for your performance, if unhelpful, try and create a productive self-talk statement to counteract the negative thought. Finally, create a routine that helps you recalibrate and reset after a long day of training or competition.`,
  },
  {
    name: MindBalanceAdultCluster.ResilientMindset,
    language: Language.English,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'You may support yourself in general, but would benefit from giving yourself a break when you don\'t meet your expectations. During challenging times, negative thoughts may become intrusive which can lead to self-criticism, allowing little margin for error. Athletes with high scores in this area consistently believe in themselves and can quickly recover from setbacks. They understand their self-worth is not defined by their performance, but by their ability to continuously push forward and bounce back. You may have these views occasionally, but may waiver in certain situations.',
    developmentalOpportunity: `To improve this area, notice your inner critic when it appears and ask yourself whether such thoughts help you be the athlete you want to be. If you notice your inner critic taking over, ask yourself if these thoughts are helpful or unhelpful for your performance, if unhelpful, try and create a productive self-talk statement to counteract the negative thought. Finally, create a routine that helps you recalibrate and reset after a long day of training or competition.`,
  },
  {
    name: MindBalanceAdultCluster.ResilientMindset,
    language: Language.English,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'You may support yourself in general, but would benefit from giving yourself a break when you don\'t meet your expectations. During challenging times, negative thoughts may become intrusive which can lead to self-criticism, allowing little margin for error. Athletes with high scores in this area consistently believe in themselves and can quickly recover from setbacks. They understand their self-worth is not defined by their performance, but by their ability to continuously push forward and bounce back. You may have these views occasionally, but may waiver in certain situations.',
    developmentalOpportunity: `To improve this area, notice your inner critic when it appears and ask yourself whether such thoughts help you be the athlete you want to be. If you notice your inner critic taking over, ask yourself if these thoughts are helpful or unhelpful for your performance, if unhelpful, try and create a productive self-talk statement to counteract the negative thought. Finally, create a routine that helps you recalibrate and reset after a long day of training or competition.`,
  },
  {
    name: MindBalanceAdultCluster.ResilientMindset,
    language: Language.English,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'You are typically kind to yourself when faced with mistakes and adversity. Athletes who score highly in this area typically believe in themselves and their abilities, regardless of the situation. They are usually able to let go of setbacks and negative thoughts that arise during training and competition. They also understand that their self-worth is not defined by their performance in sport.',
    developmentalOpportunity: `To maintain high levels of a Resilient Mindset, continue with your current effective routine and practices. Incorporating mindfulness skills to stay in the right headspace when faced with adversity may also be helpful. Set a meaningful routine to recenter and recharge as needed. Remember, imperfection is a gateway toward improvement. View adversity as inevitable and think of mistakes as an opportunity to grow in sport.`,
  },
  // Mental Skills - English
  {
    name: MindBalanceAdultCluster.MentalSkills,
    language: Language.English,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'You may have room to grow in the mental side of sports. Athletes with high mental skills scores set goals related to process rather than outcome. They also use pre-performance routines, mindfulness, and imagery to help maximize their abilities.',
    developmentalOpportunity: `To increase this score, create a pre-performance routine if you don't yet have one. If you have a routine, look to adjust it. Engage in mindfulness activities, and create specific goals for each training block or competition. Reflect on your performances to identify what went well and what's worth improving. When things are not going well, use mindfulness skills to shift your focus to what's important in the moment. Finally, focus on what you have control over and let go of factors you don't have control over so you can direct your energy toward what's important.`,
  },
  {
    name: MindBalanceAdultCluster.MentalSkills,
    language: Language.English,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'You may know what effective mental skills to use, but may not be consistent in utilizing them. Alternatively, you may benefit from improvements to all aspects of your mental performance. Athletes with high mental skills scores consistently set goals related to process rather than outcome. They consistently use pre-performance routines, mindfulness, and imagery to help maximize their abilities.',
    developmentalOpportunity: `To improve this area, always engage in a pre-performance routine. Practice daily mindfulness activities and create specific goals for each training block or competition. Reflect on your performances to identify what went well and what's worth improving. When things are not going well, use mindfulness skills to shift your focus to what's important in the moment. Finally, focus on what you have control over and let go of factors you don't have control over so you can direct your energy toward what's important.`,
  },
  {
    name: MindBalanceAdultCluster.MentalSkills,
    language: Language.English,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'You may know what effective mental skills to use, but may not be consistent in utilizing them. Alternatively, you may benefit from improvements to all aspects of your mental performance. Athletes with high mental skills scores consistently set goals related to process rather than outcome. They consistently use pre-performance routines, mindfulness, and imagery to help maximize their abilities.',
    developmentalOpportunity: `To improve this area, always engage in a pre-performance routine. Practice daily mindfulness activities and create specific goals for each training block or competition. Reflect on your performances to identify what went well and what's worth improving. When things are not going well, use mindfulness skills to shift your focus to what's important in the moment. Finally, focus on what you have control over and let go of factors you don't have control over so you can direct your energy toward what's important.`,
  },
  {
    name: MindBalanceAdultCluster.MentalSkills,
    language: Language.English,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'You may know what effective mental skills to use, but may not be consistent in utilizing them. Alternatively, you may benefit from improvements to all aspects of your mental performance. Athletes with high mental skills scores consistently set goals related to process rather than outcome. They consistently use pre-performance routines, mindfulness, and imagery to help maximize their abilities.',
    developmentalOpportunity: `To improve this area, always engage in a pre-performance routine. Practice daily mindfulness activities and create specific goals for each training block or competition. Reflect on your performances to identify what went well and what's worth improving. When things are not going well, use mindfulness skills to shift your focus to what's important in the moment. Finally, focus on what you have control over and let go of factors you don't have control over so you can direct your energy toward what's important.`,
  },
  {
    name: MindBalanceAdultCluster.MentalSkills,
    language: Language.English,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'You likely apply important sport psychology skills to your daily life. Athletes with high mental skills scores set goals related to process rather than outcome. They also use pre-performance routines, mindfulness, and imagery to maximize their abilities.',
    developmentalOpportunity: `To maintain your score in this area, continue to implement and dial in your pre-performance routine. Practice daily mindfulness activities, and revisit your goals regularly throughout the season. Reflect on your performances each week to identify what went well and what's worth improving. When things are not going well, use mindfulness skills to shift your focus to what's important in the moment. Finally, focus on what you have control over and let go of factors you don't have control over so you can direct your energy toward what's important.`,
  },
  // Team Environment - English
  {
    name: MindBalanceAdultCluster.TeamSupport,
    language: Language.English,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'Athletes with low scores in this area may feel distant from teammates and coaches and may not feel like they have meaningful connections with coaches or teammates. You may also feel as though your value on the team depends on your performance or the outcome of competition.',
    developmentalOpportunity: `To generate a stronger team environment, reflect on your strengths and what you can bring to the team. Get to know members of your team outside of training and competition by reaching out and opening up to them. You may also consider speaking with your coach or teammates to share how you've been feeling, and explore opportunities for the team to strengthen its relationships with one another.`,
  },
  {
    name: MindBalanceAdultCluster.TeamSupport,
    language: Language.English,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'You may feel generally supported by your team, but it may feel like the environment is inconsistent or depends on your performance.',
    developmentalOpportunity: `To improve this score, reflect on when you've felt the most support by your team. Think about the times you felt cared for as an athlete AND as an individual (beyond sport). This can help you become aware of opportunities to connect with others on a more personal level. Pay particular attention to moments where you may distance yourself from others (e.g., when not performing well, when stressed). You may also consider speaking with your coach or teammates to share how you've been feeling, and explore opportunities for the team to strengthen its relationships with one another.`,
  },
  {
    name: MindBalanceAdultCluster.TeamSupport,
    language: Language.English,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'You may feel generally supported by your team, but it may feel like the environment is inconsistent or depends on your performance.',
    developmentalOpportunity: `To improve this score, reflect on when you've felt the most support by your team. Think about the times you felt cared for as an athlete AND as an individual (beyond sport). This can help you become aware of opportunities to connect with others on a more personal level. Pay particular attention to moments where you may distance yourself from others (e.g., when not performing well, when stressed). You may also consider speaking with your coach or teammates to share how you've been feeling, and explore opportunities for the team to strengthen its relationships with one another.`,
  },
  {
    name: MindBalanceAdultCluster.TeamSupport,
    language: Language.English,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'You may feel generally supported by your team, but it may feel like the environment is inconsistent or depends on your performance.',
    developmentalOpportunity: `To improve this score, reflect on when you've felt the most support by your team. Think about the times you felt cared for as an athlete AND as an individual (beyond sport). This can help you become aware of opportunities to connect with others on a more personal level. Pay particular attention to moments where you may distance yourself from others (e.g., when not performing well, when stressed). You may also consider speaking with your coach or teammates to share how you've been feeling, and explore opportunities for the team to strengthen its relationships with one another.`,
  },
  {
    name: MindBalanceAdultCluster.TeamSupport,
    language: Language.English,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Athletes with high scores in this category feel like they have strong, meaningful connections with teammates and coaches. You likely feel that your team cares about your wellbeing and sees you as more than an athlete. You\'re likely to have open and honest conversations with coaches, and you know your voice is heard and valued. Athletes with high team environment scores also feel valued regardless of how they perform.',
    developmentalOpportunity: `To maintain this score, continue to maintain open lines of communication with your teammates and coaches. Team communication sparks a domino effect, allowing others to feel heard and supported. Finally, remember to communicate your appreciation to those who have supported you on your journey thus far.`,
  },
  // Health Habits - English
  {
    name: MindBalanceAdultCluster.HealthHabits,
    language: Language.English,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'You may be struggling to prioritize health habits. Athletes with low scores in this area tend to have inconsistent sleep, nutrition, and hydration patterns. They also tend to ignore important warning signs regarding injuries and burnout.',
    developmentalOpportunity: `To improve your scores in this area, dial in your sleep patterns and habits so you get consistent high quality sleep. Create a sleep routine so it's easy to wind down at night. Ask yourself whether your current hydration and nutrition regimen supports your wellness and performance goals. Prioritize the recovery process by reducing physical and mental stress on your recovery days. Finally, share potential concerns with coaching staff to prevent injuries, plateaus, or burnout.`,
  },
  {
    name: MindBalanceAdultCluster.HealthHabits,
    language: Language.English,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'Athletes with high scores in this area prioritize sleep, nutrition, and the recovery process--particularly during intense training periods. You likely practice some of these behaviors, but they may not yet be consistent or considered routine. Additionally, you may practice all of these behaviors, however there is room for improvement in your habits.',
    developmentalOpportunity: `To improve your scores in this area, dial in your sleep patterns and habits so you get consistent high quality sleep. Create a sleep routine so it's easy to wind down at night. Ask yourself whether your current hydration and nutrition regimen supports your wellness and performance goals. Prioritize the recovery process by reducing physical and mental stress on your recovery days. Finally, share potential concerns with coaching staff to prevent injuries, plateaus, or burnout.`,
  },
  {
    name: MindBalanceAdultCluster.HealthHabits,
    language: Language.English,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'Athletes with high scores in this area prioritize sleep, nutrition, and the recovery process--particularly during intense training periods. You likely practice some of these behaviors, but they may not yet be consistent or considered routine. Additionally, you may practice all of these behaviors, however there is room for improvement in your habits.',
    developmentalOpportunity: `To improve your scores in this area, dial in your sleep patterns and habits so you get consistent high quality sleep. Create a sleep routine so it's easy to wind down at night. Ask yourself whether your current hydration and nutrition regimen supports your wellness and performance goals. Prioritize the recovery process by reducing physical and mental stress on your recovery days. Finally, share potential concerns with coaching staff to prevent injuries, plateaus, or burnout.`,
  },
  {
    name: MindBalanceAdultCluster.HealthHabits,
    language: Language.English,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'Athletes with high scores in this area prioritize sleep, nutrition, and the recovery process--particularly during intense training periods. You likely practice some of these behaviors, but they may not yet be consistent or considered routine. Additionally, you may practice all of these behaviors, however there is room for improvement in your habits.',
    developmentalOpportunity: `To improve your scores in this area, dial in your sleep patterns and habits so you get consistent high quality sleep. Create a sleep routine so it's easy to wind down at night. Ask yourself whether your current hydration and nutrition regimen supports your wellness and performance goals. Prioritize the recovery process by reducing physical and mental stress on your recovery days. Finally, share potential concerns with coaching staff to prevent injuries, plateaus, or burnout.`,
  },
  {
    name: MindBalanceAdultCluster.HealthHabits,
    language: Language.English,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'You likely prioritize your physical health as an athlete. Athletes who score high in this area prioritize sleep, nutrition, and the recovery process--particularly during intense training periods.',
    developmentalOpportunity: `To maintain your score in this area, continue to prioritize your sleep by creating or sticking with a regular bedtime routine, minimizing screen time before bed, reducing ambient lights and sounds, and sleeping in a dark and cool environment. Make sure your current hydration and nutrition regimen supports your wellness and performance goals. Prioritize the recovery process by minimizing physical and mental stress on your recovery days. Finally, be sure to share potential concerns with coaching staff in order to prevent injuries, plateaus, or burnout.`,
  },
  // Wellness Accountability - English
  {
    name: MindBalanceAdultCluster.WellnessAccountability,
    language: Language.English,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'Athletes with low scores in this area are not likely to take advantage of sport psychology or counseling resources when available to them. They may not intentionally reflect on how their personal circumstances, backgrounds, or cultural identities contribute to their role in sport. However, taking time to self-reflect is crucial to growth!',
    developmentalOpportunity: `To improve your score in this area, speak with your coach or a team member to learn about the resources that are available to you. Consider whether there are barriers to seeking care when needed, such as stigma or a lack of information about resources. Additionally, take some time to reflect on how your identities and experiences affect your wellness in and outside of sport.`,
  },
  {
    name: MindBalanceAdultCluster.WellnessAccountability,
    language: Language.English,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'You may be open to using some mental health resources on occasion, but may not speak about it openly or use them regularly. You likely have a general understanding of how your identities and past experiences affect you today.',
    developmentalOpportunity: `To improve your score in this area, consider taking advantage of counseling, sport psychology, or other resources available to you as an athlete. Take some time to intentionally reflect on your background, your cultural identities, and how they have shaped you as an athlete. Finally, consider opening up to others you trust about your mental and physical health, particularly when feeling stressed or in need of additional support.`,
  },
  {
    name: MindBalanceAdultCluster.WellnessAccountability,
    language: Language.English,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'You may be open to using some mental health resources on occasion, but may not speak about it openly or use them regularly. You likely have a general understanding of how your identities and past experiences affect you today.',
    developmentalOpportunity: `To improve your score in this area, consider taking advantage of counseling, sport psychology, or other resources available to you as an athlete. Take some time to intentionally reflect on your background, your cultural identities, and how they have shaped you as an athlete. Finally, consider opening up to others you trust about your mental and physical health, particularly when feeling stressed or in need of additional support.`,
  },
  {
    name: MindBalanceAdultCluster.WellnessAccountability,
    language: Language.English,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'You may be open to using some mental health resources on occasion, but may not speak about it openly or use them regularly. You likely have a general understanding of how your identities and past experiences affect you today.',
    developmentalOpportunity: `To improve your score in this area, consider taking advantage of counseling, sport psychology, or other resources available to you as an athlete. Take some time to intentionally reflect on your background, your cultural identities, and how they have shaped you as an athlete. Finally, consider opening up to others you trust about your mental and physical health, particularly when feeling stressed or in need of additional support.`,
  },
  {
    name: MindBalanceAdultCluster.WellnessAccountability,
    language: Language.English,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'You likely engage in accountability on a regular basis to understand how experiences affect you as an athlete and as an overall person. Athletes with high scores in this area are likely to use professional resources to support their mental health when needed, and are likely to discuss their experiences openly and honestly with others.',
    developmentalOpportunity: `To maintain your score in this area, continue to reflect on how your experiences in and outside of sport affect your wellness. Consider how your identities and experiences shape who you are as an athlete. Use the resources that are available when you notice changes in your mental health that could affect your performance and your overall well-being as an athlete.`,
  },
  // Mentalidad Resiliente - Spanish
  {
    name: MindBalanceAdultCluster.ResilientMindset,
    language: Language.Spanish,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'En tu experiencia deportiva, puedes buscar la perfección, lo que puede hacerte sentir retenido por pensamientos negativos que surgen durante el entrenamiento y la competencia. También puedes establecer expectativas altas para ti mismo y sentir presión para tener éxito. Los atletas con puntuaciones en este rango a menudo sienten que su autoestima se basa en su rendimiento o habilidades. Este patrón de pensamiento puede llevar al miedo al fracaso, la autocrítica y la ansiedad cuando te empujan fuera de tu zona de confort.',
    developmentalOpportunity: `Para mejorar tu Mentalidad Resiliente, responde a tus errores con curiosidad. Pregúntate qué te causó no tener éxito y qué puedes aprender de este error. Enmarca las imperfecciones como oportunidades de aprendizaje. Al volverte más consciente de tu diálogo interno, puedes amortiguar tu crítico interno y reconstruir un diálogo interno que apoye tu resiliencia.`,
  },
  {
    name: MindBalanceAdultCluster.ResilientMindset,
    language: Language.Spanish,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'Puedes apoyarte a ti mismo en general, pero te beneficiarías de darte un respiro cuando no cumples con tus expectativas. Durante tiempos desafiantes, los pensamientos negativos pueden volverse intrusivos, lo que puede llevar a la autocrítica, permitiendo poco margen de error. Los atletas con puntuaciones altas en esta área creen consistentemente en sí mismos y pueden recuperarse rápidamente de los contratiempos. Entienden que su autoestima no está definida por su rendimiento, sino por su capacidad de avanzar continuamente y recuperarse. Puedes tener estas opiniones ocasionalmente, pero puedes vacilar en ciertas situaciones.',
    developmentalOpportunity: `Para mejorar esta área, nota tu crítico interno cuando aparezca y pregúntate si tales pensamientos te ayudan a ser el atleta que quieres ser. Si notas que tu crítico interno se está apoderando, pregúntate si estos pensamientos son útiles o inútiles para tu rendimiento; si son inútiles, intenta crear una declaración de autodiscurso productiva para contrarrestar el pensamiento negativo. Finalmente, crea una rutina que te ayude a recalibrar y reiniciar después de un largo día de entrenamiento o competencia.`,
  },
  {
    name: MindBalanceAdultCluster.ResilientMindset,
    language: Language.Spanish,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'Puedes apoyarte a ti mismo en general, pero te beneficiarías de darte un respiro cuando no cumples con tus expectativas. Durante tiempos desafiantes, los pensamientos negativos pueden volverse intrusivos, lo que puede llevar a la autocrítica, permitiendo poco margen de error. Los atletas con puntuaciones altas en esta área creen consistentemente en sí mismos y pueden recuperarse rápidamente de los contratiempos. Entienden que su autoestima no está definida por su rendimiento, sino por su capacidad de avanzar continuamente y recuperarse. Puedes tener estas opiniones ocasionalmente, pero puedes vacilar en ciertas situaciones.',
    developmentalOpportunity: `Para mejorar esta área, nota tu crítico interno cuando aparezca y pregúntate si tales pensamientos te ayudan a ser el atleta que quieres ser. Si notas que tu crítico interno se está apoderando, pregúntate si estos pensamientos son útiles o inútiles para tu rendimiento; si son inútiles, intenta crear una declaración de autodiscurso productiva para contrarrestar el pensamiento negativo. Finalmente, crea una rutina que te ayude a recalibrar y reiniciar después de un largo día de entrenamiento o competencia.`,
  },
  {
    name: MindBalanceAdultCluster.ResilientMindset,
    language: Language.Spanish,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'Puedes apoyarte a ti mismo en general, pero te beneficiarías de darte un respiro cuando no cumples con tus expectativas. Durante tiempos desafiantes, los pensamientos negativos pueden volverse intrusivos, lo que puede llevar a la autocrítica, permitiendo poco margen de error. Los atletas con puntuaciones altas en esta área creen consistentemente en sí mismos y pueden recuperarse rápidamente de los contratiempos. Entienden que su autoestima no está definida por su rendimiento, sino por su capacidad de avanzar continuamente y recuperarse. Puedes tener estas opiniones ocasionalmente, pero puedes vacilar en ciertas situaciones.',
    developmentalOpportunity: `Para mejorar esta área, nota tu crítico interno cuando aparezca y pregúntate si tales pensamientos te ayudan a ser el atleta que quieres ser. Si notas que tu crítico interno se está apoderando, pregúntate si estos pensamientos son útiles o inútiles para tu rendimiento; si son inútiles, intenta crear una declaración de autodiscurso productiva para contrarrestar el pensamiento negativo. Finalmente, crea una rutina que te ayude a recalibrar y reiniciar después de un largo día de entrenamiento o competencia.`,
  },
  {
    name: MindBalanceAdultCluster.ResilientMindset,
    language: Language.Spanish,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Típicamente eres amable contigo mismo cuando te enfrentas a errores y adversidad. Los atletas que obtienen puntuaciones altas en esta área típicamente creen en sí mismos y en sus habilidades, independientemente de la situación. Generalmente pueden dejar ir los contratiempos y los pensamientos negativos que surgen durante el entrenamiento y la competencia. También entienden que su autoestima no está definida por su rendimiento en el deporte.',
    developmentalOpportunity: `Para mantener altos niveles de una Mentalidad Resiliente, continúa con tu rutina y prácticas efectivas actuales. Incorporar habilidades de atención plena para mantener el estado mental correcto cuando te enfrentes a la adversidad también puede ser útil. Establece una rutina significativa para recentrar y recargar según sea necesario. Recuerda, la imperfección es una puerta hacia la mejora. Ve la adversidad como inevitable y piensa en los errores como una oportunidad para crecer en el deporte.`,
  },
  // Habilidades Mentales - Spanish
  {
    name: MindBalanceAdultCluster.MentalSkills,
    language: Language.Spanish,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'Puedes tener espacio para crecer en el aspecto mental de los deportes. Los atletas con puntuaciones altas en habilidades mentales establecen metas relacionadas con el proceso en lugar del resultado. También usan rutinas previas al rendimiento, atención plena e imaginería para ayudar a maximizar sus habilidades.',
    developmentalOpportunity: `Para aumentar esta puntuación, crea una rutina previa al rendimiento si aún no tienes una. Si tienes una rutina, busca ajustarla. Participa en actividades de atención plena y crea metas específicas para cada bloque de entrenamiento o competencia. Reflexiona sobre tus actuaciones para identificar qué salió bien y qué vale la pena mejorar. Cuando las cosas no van bien, usa habilidades de atención plena para cambiar tu enfoque a lo que es importante en el momento. Finalmente, enfócate en lo que tienes control y deja ir los factores sobre los que no tienes control para que puedas dirigir tu energía hacia lo que es importante.`,
  },
  {
    name: MindBalanceAdultCluster.MentalSkills,
    language: Language.Spanish,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'Puedes saber qué habilidades mentales efectivas usar, pero puede que no seas consistente en utilizarlas. Alternativamente, puedes beneficiarte de mejoras en todos los aspectos de tu rendimiento mental. Los atletas con puntuaciones altas en habilidades mentales establecen consistentemente metas relacionadas con el proceso en lugar del resultado. Usan consistentemente rutinas previas al rendimiento, atención plena e imaginería para ayudar a maximizar sus habilidades.',
    developmentalOpportunity: `Para mejorar esta área, siempre participa en una rutina previa al rendimiento. Practica actividades diarias de atención plena y crea metas específicas para cada bloque de entrenamiento o competencia. Reflexiona sobre tus actuaciones para identificar qué salió bien y qué vale la pena mejorar. Cuando las cosas no van bien, usa habilidades de atención plena para cambiar tu enfoque a lo que es importante en el momento. Finalmente, enfócate en lo que tienes control y deja ir los factores sobre los que no tienes control para que puedas dirigir tu energía hacia lo que es importante.`,
  },
  {
    name: MindBalanceAdultCluster.MentalSkills,
    language: Language.Spanish,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'Puedes saber qué habilidades mentales efectivas usar, pero puede que no seas consistente en utilizarlas. Alternativamente, puedes beneficiarte de mejoras en todos los aspectos de tu rendimiento mental. Los atletas con puntuaciones altas en habilidades mentales establecen consistentemente metas relacionadas con el proceso en lugar del resultado. Usan consistentemente rutinas previas al rendimiento, atención plena e imaginería para ayudar a maximizar sus habilidades.',
    developmentalOpportunity: `Para mejorar esta área, siempre participa en una rutina previa al rendimiento. Practica actividades diarias de atención plena y crea metas específicas para cada bloque de entrenamiento o competencia. Reflexiona sobre tus actuaciones para identificar qué salió bien y qué vale la pena mejorar. Cuando las cosas no van bien, usa habilidades de atención plena para cambiar tu enfoque a lo que es importante en el momento. Finalmente, enfócate en lo que tienes control y deja ir los factores sobre los que no tienes control para que puedas dirigir tu energía hacia lo que es importante.`,
  },
  {
    name: MindBalanceAdultCluster.MentalSkills,
    language: Language.Spanish,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'Puedes saber qué habilidades mentales efectivas usar, pero puede que no seas consistente en utilizarlas. Alternativamente, puedes beneficiarte de mejoras en todos los aspectos de tu rendimiento mental. Los atletas con puntuaciones altas en habilidades mentales establecen consistentemente metas relacionadas con el proceso en lugar del resultado. Usan consistentemente rutinas previas al rendimiento, atención plena e imaginería para ayudar a maximizar sus habilidades.',
    developmentalOpportunity: `Para mejorar esta área, siempre participa en una rutina previa al rendimiento. Practica actividades diarias de atención plena y crea metas específicas para cada bloque de entrenamiento o competencia. Reflexiona sobre tus actuaciones para identificar qué salió bien y qué vale la pena mejorar. Cuando las cosas no van bien, usa habilidades de atención plena para cambiar tu enfoque a lo que es importante en el momento. Finalmente, enfócate en lo que tienes control y deja ir los factores sobre los que no tienes control para que puedas dirigir tu energía hacia lo que es importante.`,
  },
  {
    name: MindBalanceAdultCluster.MentalSkills,
    language: Language.Spanish,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Probablemente aplicas habilidades importantes de psicología del deporte a tu vida diaria. Los atletas con puntuaciones altas en habilidades mentales establecen metas relacionadas con el proceso en lugar del resultado. También usan rutinas previas al rendimiento, atención plena e imaginería para maximizar sus habilidades.',
    developmentalOpportunity: `Para mantener tu puntuación en esta área, continúa implementando y ajustando tu rutina previa al rendimiento. Practica actividades diarias de atención plena y revisa tus metas regularmente durante la temporada. Reflexiona sobre tus actuaciones cada semana para identificar qué salió bien y qué vale la pena mejorar. Cuando las cosas no van bien, usa habilidades de atención plena para cambiar tu enfoque a lo que es importante en el momento. Finalmente, enfócate en lo que tienes control y deja ir los factores sobre los que no tienes control para que puedas dirigir tu energía hacia lo que es importante.`,
  },
  // Ambiente de Equipo - Spanish
  {
    name: MindBalanceAdultCluster.TeamSupport,
    language: Language.Spanish,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'Los atletas con puntuaciones bajas en esta área pueden sentirse distantes de sus compañeros de equipo y entrenadores y pueden no sentir que tienen conexiones significativas con entrenadores o compañeros de equipo. También puedes sentir que tu valor en el equipo depende de tu rendimiento o del resultado de la competencia.',
    developmentalOpportunity: `Para generar un ambiente de equipo más fuerte, reflexiona sobre tus fortalezas y lo que puedes aportar al equipo. Conoce a los miembros de tu equipo fuera del entrenamiento y la competencia acercándote y abriéndote a ellos. También puedes considerar hablar con tu entrenador o compañeros de equipo para compartir cómo te has estado sintiendo, y explorar oportunidades para que el equipo fortalezca sus relaciones entre sí.`,
  },
  {
    name: MindBalanceAdultCluster.TeamSupport,
    language: Language.Spanish,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'Puedes sentirte generalmente apoyado por tu equipo, pero puede parecer que el ambiente es inconsistente o depende de tu rendimiento.',
    developmentalOpportunity: `Para mejorar esta puntuación, reflexiona sobre cuándo has sentido el mayor apoyo por parte de tu equipo. Piensa en las veces que te sentiste cuidado como atleta Y como individuo (más allá del deporte). Esto puede ayudarte a ser consciente de las oportunidades para conectarte con otros en un nivel más personal. Presta especial atención a los momentos en los que puedes distanciarte de otros (por ejemplo, cuando no te desempeñas bien, cuando estás estresado). También puedes considerar hablar con tu entrenador o compañeros de equipo para compartir cómo te has estado sintiendo, y explorar oportunidades para que el equipo fortalezca sus relaciones entre sí.`,
  },
  {
    name: MindBalanceAdultCluster.TeamSupport,
    language: Language.Spanish,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'Puedes sentirte generalmente apoyado por tu equipo, pero puede parecer que el ambiente es inconsistente o depende de tu rendimiento.',
    developmentalOpportunity: `Para mejorar esta puntuación, reflexiona sobre cuándo has sentido el mayor apoyo por parte de tu equipo. Piensa en las veces que te sentiste cuidado como atleta Y como individuo (más allá del deporte). Esto puede ayudarte a ser consciente de las oportunidades para conectarte con otros en un nivel más personal. Presta especial atención a los momentos en los que puedes distanciarte de otros (por ejemplo, cuando no te desempeñas bien, cuando estás estresado). También puedes considerar hablar con tu entrenador o compañeros de equipo para compartir cómo te has estado sintiendo, y explorar oportunidades para que el equipo fortalezca sus relaciones entre sí.`,
  },
  {
    name: MindBalanceAdultCluster.TeamSupport,
    language: Language.Spanish,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'Puedes sentirte generalmente apoyado por tu equipo, pero puede parecer que el ambiente es inconsistente o depende de tu rendimiento.',
    developmentalOpportunity: `Para mejorar esta puntuación, reflexiona sobre cuándo has sentido el mayor apoyo por parte de tu equipo. Piensa en las veces que te sentiste cuidado como atleta Y como individuo (más allá del deporte). Esto puede ayudarte a ser consciente de las oportunidades para conectarte con otros en un nivel más personal. Presta especial atención a los momentos en los que puedes distanciarte de otros (por ejemplo, cuando no te desempeñas bien, cuando estás estresado). También puedes considerar hablar con tu entrenador o compañeros de equipo para compartir cómo te has estado sintiendo, y explorar oportunidades para que el equipo fortalezca sus relaciones entre sí.`,
  },
  {
    name: MindBalanceAdultCluster.TeamSupport,
    language: Language.Spanish,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Los atletas con puntuaciones altas en esta categoría sienten que tienen conexiones fuertes y significativas con sus compañeros de equipo y entrenadores. Es probable que sientas que tu equipo se preocupa por tu bienestar y te ve como más que un atleta. Es probable que tengas conversaciones abiertas y honestas con los entrenadores, y sabes que tu voz es escuchada y valorada. Los atletas con puntuaciones altas de ambiente de equipo también se sienten valorados independientemente de cómo se desempeñen.',
    developmentalOpportunity: `Para mantener esta puntuación, continúa manteniendo líneas abiertas de comunicación con tus compañeros de equipo y entrenadores. La comunicación del equipo genera un efecto dominó, permitiendo que otros se sientan escuchados y apoyados. Finalmente, recuerda comunicar tu aprecio a aquellos que te han apoyado en tu viaje hasta ahora.`,
  },
  // Hábitos de Salud - Spanish
  {
    name: MindBalanceAdultCluster.HealthHabits,
    language: Language.Spanish,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'Puedes estar luchando por priorizar los hábitos de salud. Los atletas con puntuaciones bajas en esta área tienden a tener patrones inconsistentes de sueño, nutrición e hidratación. También tienden a ignorar señales de advertencia importantes sobre lesiones y agotamiento.',
    developmentalOpportunity: `Para mejorar tus puntuaciones en esta área, ajusta tus patrones y hábitos de sueño para que obtengas un sueño de alta calidad y consistente. Crea una rutina de sueño para que sea fácil relajarse por la noche. Pregúntate si tu régimen actual de hidratación y nutrición apoya tus objetivos de bienestar y rendimiento. Prioriza el proceso de recuperación reduciendo el estrés físico y mental en tus días de recuperación. Finalmente, comparte preocupaciones potenciales con el personal de entrenamiento para prevenir lesiones, estancamientos o agotamiento.`,
  },
  {
    name: MindBalanceAdultCluster.HealthHabits,
    language: Language.Spanish,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'Los atletas con puntuaciones altas en esta área priorizan el sueño, la nutrición y el proceso de recuperación, particularmente durante períodos de entrenamiento intenso. Es probable que practiques algunos de estos comportamientos, pero pueden no ser aún consistentes o considerados rutinarios. Además, puedes practicar todos estos comportamientos, sin embargo hay margen de mejora en tus hábitos.',
    developmentalOpportunity: `Para mejorar tus puntuaciones en esta área, ajusta tus patrones y hábitos de sueño para que obtengas un sueño de alta calidad y consistente. Crea una rutina de sueño para que sea fácil relajarse por la noche. Pregúntate si tu régimen actual de hidratación y nutrición apoya tus objetivos de bienestar y rendimiento. Prioriza el proceso de recuperación reduciendo el estrés físico y mental en tus días de recuperación. Finalmente, comparte preocupaciones potenciales con el personal de entrenamiento para prevenir lesiones, estancamientos o agotamiento.`,
  },
  {
    name: MindBalanceAdultCluster.HealthHabits,
    language: Language.Spanish,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'Los atletas con puntuaciones altas en esta área priorizan el sueño, la nutrición y el proceso de recuperación, particularmente durante períodos de entrenamiento intenso. Es probable que practiques algunos de estos comportamientos, pero pueden no ser aún consistentes o considerados rutinarios. Además, puedes practicar todos estos comportamientos, sin embargo hay margen de mejora en tus hábitos.',
    developmentalOpportunity: `Para mejorar tus puntuaciones en esta área, ajusta tus patrones y hábitos de sueño para que obtengas un sueño de alta calidad y consistente. Crea una rutina de sueño para que sea fácil relajarse por la noche. Pregúntate si tu régimen actual de hidratación y nutrición apoya tus objetivos de bienestar y rendimiento. Prioriza el proceso de recuperación reduciendo el estrés físico y mental en tus días de recuperación. Finalmente, comparte preocupaciones potenciales con el personal de entrenamiento para prevenir lesiones, estancamientos o agotamiento.`,
  },
  {
    name: MindBalanceAdultCluster.HealthHabits,
    language: Language.Spanish,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'Los atletas con puntuaciones altas en esta área priorizan el sueño, la nutrición y el proceso de recuperación, particularmente durante períodos de entrenamiento intenso. Es probable que practiques algunos de estos comportamientos, pero pueden no ser aún consistentes o considerados rutinarios. Además, puedes practicar todos estos comportamientos, sin embargo hay margen de mejora en tus hábitos.',
    developmentalOpportunity: `Para mejorar tus puntuaciones en esta área, ajusta tus patrones y hábitos de sueño para que obtengas un sueño de alta calidad y consistente. Crea una rutina de sueño para que sea fácil relajarse por la noche. Pregúntate si tu régimen actual de hidratación y nutrición apoya tus objetivos de bienestar y rendimiento. Prioriza el proceso de recuperación reduciendo el estrés físico y mental en tus días de recuperación. Finalmente, comparte preocupaciones potenciales con el personal de entrenamiento para prevenir lesiones, estancamientos o agotamiento.`,
  },
  {
    name: MindBalanceAdultCluster.HealthHabits,
    language: Language.Spanish,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Es probable que priorices tu salud física como atleta. Los atletas que obtienen puntuaciones altas en esta área priorizan el sueño, la nutrición y el proceso de recuperación, particularmente durante períodos de entrenamiento intenso.',
    developmentalOpportunity: `Para mantener tu puntuación en esta área, continúa priorizando tu sueño creando o manteniendo una rutina regular de hora de acostarse, minimizando el tiempo de pantalla antes de acostarse, reduciendo las luces y sonidos ambientales, y durmiendo en un ambiente oscuro y fresco. Asegúrate de que tu régimen actual de hidratación y nutrición apoye tus objetivos de bienestar y rendimiento. Prioriza el proceso de recuperación minimizando el estrés físico y mental en tus días de recuperación. Finalmente, asegúrate de compartir preocupaciones potenciales con el personal de entrenamiento para prevenir lesiones, estancamientos o agotamiento.`,
  },
  // Responsabilidad del Bienestar - Spanish
  {
    name: MindBalanceAdultCluster.WellnessAccountability,
    language: Language.Spanish,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'Los atletas con puntuaciones bajas en esta área no es probable que aprovechen los recursos de psicología del deporte o asesoramiento cuando están disponibles para ellos. Pueden no reflexionar intencionalmente sobre cómo sus circunstancias personales, antecedentes o identidades culturales contribuyen a su papel en el deporte. Sin embargo, ¡tomarse el tiempo para autorreflexionar es crucial para el crecimiento!',
    developmentalOpportunity: `Para mejorar tu puntuación en esta área, habla con tu entrenador o un miembro del equipo para aprender sobre los recursos que están disponibles para ti. Considera si hay barreras para buscar atención cuando sea necesario, como el estigma o la falta de información sobre los recursos. Además, tómate un tiempo para reflexionar sobre cómo tus identidades y experiencias afectan tu bienestar dentro y fuera del deporte.`,
  },
  {
    name: MindBalanceAdultCluster.WellnessAccountability,
    language: Language.Spanish,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'Puedes estar abierto a usar algunos recursos de salud mental ocasionalmente, pero puede que no hables de ello abiertamente o los uses regularmente. Es probable que tengas una comprensión general de cómo tus identidades y experiencias pasadas te afectan hoy.',
    developmentalOpportunity: `Para mejorar tu puntuación en esta área, considera aprovechar el asesoramiento, la psicología del deporte u otros recursos disponibles para ti como atleta. Tómate un tiempo para reflexionar intencionalmente sobre tus antecedentes, tus identidades culturales y cómo te han moldeado como atleta. Finalmente, considera abrirte a otros en quienes confías sobre tu salud mental y física, particularmente cuando te sientas estresado o necesites apoyo adicional.`,
  },
  {
    name: MindBalanceAdultCluster.WellnessAccountability,
    language: Language.Spanish,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'Puedes estar abierto a usar algunos recursos de salud mental ocasionalmente, pero puede que no hables de ello abiertamente o los uses regularmente. Es probable que tengas una comprensión general de cómo tus identidades y experiencias pasadas te afectan hoy.',
    developmentalOpportunity: `Para mejorar tu puntuación en esta área, considera aprovechar el asesoramiento, la psicología del deporte u otros recursos disponibles para ti como atleta. Tómate un tiempo para reflexionar intencionalmente sobre tus antecedentes, tus identidades culturales y cómo te han moldeado como atleta. Finalmente, considera abrirte a otros en quienes confías sobre tu salud mental y física, particularmente cuando te sientas estresado o necesites apoyo adicional.`,
  },
  {
    name: MindBalanceAdultCluster.WellnessAccountability,
    language: Language.Spanish,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'Puedes estar abierto a usar algunos recursos de salud mental ocasionalmente, pero puede que no hables de ello abiertamente o los uses regularmente. Es probable que tengas una comprensión general de cómo tus identidades y experiencias pasadas te afectan hoy.',
    developmentalOpportunity: `Para mejorar tu puntuación en esta área, considera aprovechar el asesoramiento, la psicología del deporte u otros recursos disponibles para ti como atleta. Tómate un tiempo para reflexionar intencionalmente sobre tus antecedentes, tus identidades culturales y cómo te han moldeado como atleta. Finalmente, considera abrirte a otros en quienes confías sobre tu salud mental y física, particularmente cuando te sientas estresado o necesites apoyo adicional.`,
  },
  {
    name: MindBalanceAdultCluster.WellnessAccountability,
    language: Language.Spanish,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Es probable que participes en la responsabilidad de manera regular para entender cómo las experiencias te afectan como atleta y como persona en general. Los atletas con puntuaciones altas en esta área es probable que usen recursos profesionales para apoyar su salud mental cuando sea necesario, y es probable que discutan sus experiencias abierta y honestamente con otros.',
    developmentalOpportunity: `Para mantener tu puntuación en esta área, continúa reflexionando sobre cómo tus experiencias dentro y fuera del deporte afectan tu bienestar. Considera cómo tus identidades y experiencias moldean quién eres como atleta. Usa los recursos que están disponibles cuando notes cambios en tu salud mental que podrían afectar tu rendimiento y tu bienestar general como atleta.`,
  },
];

