export const percentileInterpretation = [
  {
    name: 'growth_mindset',
    minPercentile: 0,
    maxPercentile: 20,
    meaning: 'In your sporting experience, you may seek perfection which may cause you to feel held back by negative thoughts that arise while training and competing. You may also set high expectations for yourself and feel pressure to succeed. Athletes with scores in this range  often feel their self-worth is based on their performance or abilities. This pattern of thinking can lead to fear of failure, self-criticism, and anxiety when pushed outside of your comfort zone.',
    next_steps: 'To improve your Resilient Mindset, respond to your mistakes with curiosity. Ask yourself what caused you to not be successful and what can you learn from this mistake. Frame imperfections as learning opportunities. By becoming more aware of your inner dialogue, you can damper your inner critic and rebuild an inner dialogue that supports your resiliency.',
  },
  {
    name: 'growth_mindset',
    minPercentile: 30,
    maxPercentile: 80,
    meaning: 'You may support yourself in general, but would benefit from giving yourself a break when you don’t meet your expectations. During challenging times, negative thoughts may become intrusive which can lead to self-criticism, allowing little margin for error.\n\nAthletes with high scores in this area consistently believe in themselves and can quickly recover from setbacks. They understand their self-worth is not defined by their performance, but by their ability to continuously push forward and bounce back. You may have these views occasionally, but may waiver in certain situations.',
    next_steps: 'To improve this area, notice your inner critic when it appears and ask yourself whether such thoughts help you be the athlete you want to be. If you notice your inner critic taking over, ask yourself if these thoughts are helpful or unhelpful for your performance, if unhelpful, try and create a productive self-talk statement to counteract the negative thought. Finally, create a routine that helps you recalibrate and reset after a long day of training or competition.',
  },
  {
    name: 'growth_mindset',
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'You are typically kind to yourself when faced with mistakes and adversity. Athletes who score highly in this area typically believe in themselves and their abilities, regardless of the situation. They are usually able to let go of setbacks and negative thoughts that arise during training and competition. They also understand that their self-worth is not defined by their performance in sport.',
    next_steps: 'To maintain high levels of a Resilient Mindset, continue with your current effective routine and practices. Incorporating mindfulness skills to stay in the right headspace when faced with adversity may also be helpful. Set a meaningful routine to recenter and recharge as needed. Remember, imperfection is a gateway toward improvement. View adversity as inevitable and think of mistakes as an opportunity to grow in sport.',
  },
  {
    name: 'mental_skills',
    minPercentile: 0,
    maxPercentile: 20,
    meaning: 'You may have room to grow in the mental side of sports. Athletes with high mental skills scores set goals related to process rather than outcome. They also use pre-performance routines, mindfulness, and imagery to help maximize their abilities.',
    next_steps: 'To increase this score, create a pre-performance routine if you don’t yet have one. If you have a routine, look to adjust it. Engage in mindfulness activities, and create specific goals for each training block or competition. Reflect on your performances to identify what went well and what’s worth improving. When things are not going well, use mindfulness skills to shift your focus to what’s important in the moment. Finally, focus on what you have control over and let go of factors you don’t have control over so you can direct your energy toward what’s important.',
  },
  {
    name: 'mental_skills',
    minPercentile: 30,
    maxPercentile: 80,
    meaning: 'You may know what effective mental skills to use, but may not be consistent in utilizing them. Alternatively, you may benefit from improvements to all aspects of your mental performance. Athletes with high mental skills scores consistently set goals related to process rather than outcome. They consistently use pre-performance routines, mindfulness, and imagery to help maximize their abilities.',
    next_steps: 'To improve this area, always engage in a pre-performance routine. Practice daily mindfulness activities and create specific goals for each training block or competition. Reflect on your performances to identify what went well and what’s worth improving. When things are not going well, use mindfulness skills to shift your focus to what’s important in the moment. Finally, focus on what you have control over and let go of factors you don’t have control over so you can direct your energy toward what’s important.',
  },
  {
    name: 'mental_skills',
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'You likely apply important sport psychology skills to your daily life. Athletes with high mental skills scores set goals related to process rather than outcome. They also use pre-performance routines, mindfulness, and imagery to maximize their abilities.',
    next_steps: 'To maintain your score in this area, continue to implement and dial in your pre-performance routine. Practice daily mindfulness activities, and revisit your goals regularly throughout the season. Reflect on your performances each week to identify what went well and what’s worth improving. When things are not going well, use mindfulness skills to shift your focus to what’s important in the moment. Finally, focus on what you have control over and let go of factors you don’t have control over so you can direct your energy toward what’s important.',
  },
  {
    name: 'team_support',
    minPercentile: 0,
    maxPercentile: 20,
    meaning: 'Athletes with low scores in this area may feel distant from teammates and coaches and may not feel like they have meaningful connections with coaches or teammates. You may also feel as though your value on the team depends on your performance or the outcome of competition.',
    next_steps: 'To generate a stronger team environment, reflect on your strengths and what you can bring to the team. Get to know members of your team outside of training and competition by reaching out and opening up to them. You may also consider speaking with your coach or teammates to share how you’ve been feeling, and explore opportunities for the team to strengthen its relationships with one another.',
  },
  {
    name: 'team_support',
    minPercentile: 30,
    maxPercentile: 80,
    meaning: 'You may feel generally supported by your team, but it may feel like the environment is inconsistent or depends on your performance.',
    next_steps: 'To improve this score, reflect on when you’ve felt the most support by your team. Think about the times you felt cared for as an athlete AND as an individual (beyond sport). This can help you become aware of opportunities to connect with others on a more personal level. Pay particular attention to moments where you may distance yourself from others (e.g., when not performing well, when stressed). You may also consider speaking with your coach or teammates to share how you’ve been feeling, and explore opportunities for the team to strengthen its relationships with one another.',
  },
  {
    name: 'team_support',
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Athletes with high scores in this category feel like they have strong, meaningful connections with teammates and coaches. You likely feel that your team cares about your wellbeing and sees you as more than an athlete. You’re likely to have open and honest conversations with coaches, and you know your voice is heard and valued. Athletes with high team environment scores also feel valued regardless of how they perform.',
    next_steps: 'To maintain this score, continue to maintain open lines of communication with your teammates and coaches. Team communication sparks a domino effect, allowing others to feel heard and supported. Finally, remember to communicate your appreciation to those who have supported you on your journey thus far.',
  },
  {
    name: 'health_habits',
    minPercentile: 0,
    maxPercentile: 20,
    meaning: 'You may be struggling to prioritize health habits. Athletes with low scores in this area tend to have inconsistent sleep, nutrition, and hydration patterns. They also tend to ignore important warning signs regarding injuries and burnout.',
    next_steps: 'To improve your scores in this area, dial in your sleep patterns and habits so you get consistent high quality sleep. Create a sleep routine so it’s easy to wind down at night. Ask yourself whether your current hydration and nutrition regimen supports your wellness and performance goals. Prioritize the recovery process by reducing physical and mental stress on your recovery days. Finally, share potential concerns with coaching staff to prevent injuries, plateaus, or burnout.',
  },
  {
    name: 'health_habits',
    minPercentile: 30,
    maxPercentile: 80,
    meaning: 'Athletes with high scores in this area prioritize sleep, nutrition, and the recovery process--particularly during intense training periods. You likely practice some of these behaviors, but they may not yet be consistent or considered routine. Additionally, you may practice all of these behaviors, however there is room for improvement in your habits.',
    next_steps: 'To improve your scores in this area, dial in your sleep patterns and habits so you get consistent high quality sleep. Create a sleep routine so it’s easy to wind down at night. Ask yourself whether your current hydration and nutrition regimen supports your wellness and performance goals. Prioritize the recovery process by reducing physical and mental stress on your recovery days. Finally, share potential concerns with coaching staff to prevent injuries, plateaus, or burnout.',
  },
  {
    name: 'health_habits',
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'You likely prioritize your physical health as an athlete. Athletes who score high in this area prioritize sleep, nutrition, and the recovery process--particularly during intense training periods.',
    next_steps: 'To maintain your score in this area, continue to prioritize your sleep by creating or sticking with a regular bedtime routine, minimizing screen time before bed, reducing ambient lights and sounds, and sleeping in a dark and cool environment. Make sure your current hydration and nutrition regimen supports your wellness and performance goals. Prioritize the recovery process by minimizing physical and mental stress on your recovery days. Finally, be sure to share potential concerns with coaching staff in order to prevent injuries, plateaus, or burnout',
  },
  {
    name: 'self_reflection',
    minPercentile: 0,
    maxPercentile: 20,
    meaning: 'Athletes with low scores in this area are not likely to take advantage of sport psychology or counseling resources when available to them. They may not intentionally reflect on how their personal circumstances, backgrounds, or cultural identities contribute to their role in sport. However, taking time to self-reflect is crucial to growth!',
    next_steps: 'To improve your score in this area, speak with your coach or a team member to learn about the resources that are available to you. Consider whether there are barriers to seeking care when needed, such as stigma or a lack of information about resources. Additionally, take some time to reflect on how your identities and experiences affect your wellness in and outside of sport.',
  },
  {
    name: 'self_reflection',
    minPercentile: 30,
    maxPercentile: 80,
    meaning: 'TYou may be open to using some mental health resources on occasion, but may not speak about it openly or use them regularly. You likely have a general understanding of how your identities and past experiences affect you today.',
    next_steps: 'To improve your score in this area, consider taking advantage of counseling, sport psychology, or other resources available to you as an athlete. Take some time to intentionally reflect on your background, your cultural identities, and how they have shaped you as an athlete. Finally, consider opening up to others you trust about your mental and physical health, particularly when feeling stressed or in need of additional support.',
  },
  {
    name: 'self_reflection',
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'You likely engage in accountability on a regular basis to understand how experiences affect you as an athlete and as an overall person. Athletes with high scores in this area are likely to use professional resources to support their mental health when needed, and are likely to discuss their experiences openly and honestly with others.',
    next_steps: 'To maintain your score in this area, continue to reflect on how your experiences in and outside of sport affect your wellness. Consider how your identities and experiences shape who you are as an athlete. Use the resources that are available when you notice changes in your mental health that could affect your performance and your overall well-being as an athlete.',
  },
]