import { MindBalanceCluster, Language } from "../types";

export const percentileInterpretationMindBalance = [
  // Growth Mindset - English
  {
    name: MindBalanceCluster.GrowthMindset,
    language: Language.English,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'Based on your Growth Mindset score, you are still learning to deal with the pressures of competition, how to embrace challenges, and how to let go of things outside of your control. It can be hard to be consistent with important skills like those. Youth athletes with high scores in this area tend to cope well with the ups and downs in sport. They don\'t worry too much about the performance of others or the outcome of competitions. Instead, they focus on what they can control. They work hard in practice and competition to be the best athlete they can be.',
  },
  {
    name: MindBalanceCluster.GrowthMindset,
    language: Language.English,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'Your Growth Mindset score is similar to the majority of other youth athletes. This score means you can often deal with pressure, accept challenges, and let go of things outside of your control–but you might not be doing it consistently yet. Youth athletes with scores similar to yours in this area will be okay with the ups and downs in sport. They may sometimes worry about their team\'s performance and whether they are winning or losing. At times, they might be afraid to make mistakes or try new things.',
  },
  {
    name: MindBalanceCluster.GrowthMindset,
    language: Language.English,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'Your Growth Mindset score is similar to the majority of other youth athletes. This score means you can often deal with pressure, accept challenges, and let go of things outside of your control–but you might not be doing it consistently yet. Youth athletes with scores similar to yours in this area will be okay with the ups and downs in sport. They may sometimes worry about their team\'s performance and whether they are winning or losing. At times, they might be afraid to make mistakes or try new things.',
  },
  {
    name: MindBalanceCluster.GrowthMindset,
    language: Language.English,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'Your Growth Mindset score is similar to the majority of other youth athletes. This score means you can often deal with pressure, accept challenges, and let go of things outside of your control–but you might not be doing it consistently yet. Youth athletes with scores similar to yours in this area will be okay with the ups and downs in sport. They may sometimes worry about their team\'s performance and whether they are winning or losing. At times, they might be afraid to make mistakes or try new things.',
  },
  {
    name: MindBalanceCluster.GrowthMindset,
    language: Language.English,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Your Growth Mindset score is in the above average range in comparison to other youth athletes. This score shows you are learning important skills in sport that will make you a better athlete in the future. These skills include dealing with pressure, accepting challenges, and letting go of things outside of your control. Youth athletes with high scores in this area are also likely to be okay with the ups and downs in sport. They\'re not likely to worry about the performance of others or winning/losing. Instead, they focus on what they control and work hard in practice and competition to be the best athlete they can be.',
  },
  // Self-Confidence - English
  {
    name: MindBalanceCluster.SelfConfidence,
    language: Language.English,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'Your Self-Confidence score is lower compared to other youth athletes. Self-confidence is your core beliefs about yourself. Your score suggests that you are still strengthening your views and beliefs about yourself. Those who score higher in this category, use healthy coping skills. You are still in the process of learning them and applying them to your life, and that is okay!',
  },
  {
    name: MindBalanceCluster.SelfConfidence,
    language: Language.English,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'Your Self-Confidence score was similar to other youth athletes. Self-confidence is your beliefs about yourself and your abilities. This score shows that you may at times feel like you are good enough just the way you are, and other times you may feel like you are not good enough. You may know some coping skills and use them at times, but might not use them as often as you could. Athletes with scores like yours can ask questions and ask for help when needed, but may not do it as often as they could. They can deal with pressure most of the time, but may struggle with this once in a while.',
  },
  {
    name: MindBalanceCluster.SelfConfidence,
    language: Language.English,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'Your Self-Confidence score was similar to other youth athletes. Self-confidence is your beliefs about yourself and your abilities. This score shows that you may at times feel like you are good enough just the way you are, and other times you may feel like you are not good enough. You may know some coping skills and use them at times, but might not use them as often as you could. Athletes with scores like yours can ask questions and ask for help when needed, but may not do it as often as they could. They can deal with pressure most of the time, but may struggle with this once in a while.',
  },
  {
    name: MindBalanceCluster.SelfConfidence,
    language: Language.English,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'Your Self-Confidence score was similar to other youth athletes. Self-confidence is your beliefs about yourself and your abilities. This score shows that you may at times feel like you are good enough just the way you are, and other times you may feel like you are not good enough. You may know some coping skills and use them at times, but might not use them as often as you could. Athletes with scores like yours can ask questions and ask for help when needed, but may not do it as often as they could. They can deal with pressure most of the time, but may struggle with this once in a while.',
  },
  {
    name: MindBalanceCluster.SelfConfidence,
    language: Language.English,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Your Self-Confidence score was higher than other youth athletes. Self-confidence is your beliefs about yourself and your abilities. This score means you probably feel like you are good enough just the way you are. You probably keep a positive mindset and focus. You also probably know when to use healthy coping skills. Athletes with high scores in this area almost always focus on what is important, on and off the field.',
  },
  // Team Culture - English
  {
    name: MindBalanceCluster.TeamCulture,
    language: Language.English,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'Your Team Culture score tells us you feel like your teammates or community may not be supporting you enough on and off the field. You may feel distant from your team at times. Those with above average scores feel as though their value does not depend on whether they win or lose.',
  },
  {
    name: MindBalanceCluster.TeamCulture,
    language: Language.English,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'Your Team Culture score is in the average range in comparison to other youth athletes, which means you may feel supported at times, but there may be moments where you feel disconnected from your team or community. It may be that you feel supported by your team, but not your family, or vice versa. There is also a chance that you feel supported by your team and family but it depends on how you perform.',
  },
  {
    name: MindBalanceCluster.TeamCulture,
    language: Language.English,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'Your Team Culture score is in the average range in comparison to other youth athletes, which means you may feel supported at times, but there may be moments where you feel disconnected from your team or community. It may be that you feel supported by your team, but not your family, or vice versa. There is also a chance that you feel supported by your team and family but it depends on how you perform.',
  },
  {
    name: MindBalanceCluster.TeamCulture,
    language: Language.English,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'Your Team Culture score is in the average range in comparison to other youth athletes, which means you may feel supported at times, but there may be moments where you feel disconnected from your team or community. It may be that you feel supported by your team, but not your family, or vice versa. There is also a chance that you feel supported by your team and family but it depends on how you perform.',
  },
  {
    name: MindBalanceCluster.TeamCulture,
    language: Language.English,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Your Team Culture score is higher than most youth athletes. Youth athletes who score highly in this category tend to have strong, meaningful relationships with their team and community. You likely feel that people care about your wellbeing and see you as more than an athlete. You are likely to be in an environment that has open and honest conversations with others, and feel heard and valued for who you are. Youth athletes who score high in this category also feel they are valued by others no matter how they perform.',
  },
  // Health Behaviors - English
  {
    name: MindBalanceCluster.HealthBehaviors,
    language: Language.English,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'Your Health Behaviors score is in the below average range compared to other youth athletes, which means you are trying to balance sport and other areas of your life. Being dedicated to your sport can be time consuming which is why it is important to not let other important areas slip away, such as your sleep and nutrition. Youth athletes with high scores in this area feel a good balance between life and sport, limit their social media use, have good sleep habits, and eat well.',
  },
  {
    name: MindBalanceCluster.HealthBehaviors,
    language: Language.English,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'Your Health Behaviors score is in the average range in comparison to other youth athletes, which means you are likely doing some things that are important to physical health and mental health outside of sport, but have some areas to improve on. Youth athletes with high scores in this area feel a good balance between life and sport, limit their social media use, have good sleep habits, and eat well.',
  },
  {
    name: MindBalanceCluster.HealthBehaviors,
    language: Language.English,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'Your Health Behaviors score is in the average range in comparison to other youth athletes, which means you are likely doing some things that are important to physical health and mental health outside of sport, but have some areas to improve on. Youth athletes with high scores in this area feel a good balance between life and sport, limit their social media use, have good sleep habits, and eat well.',
  },
  {
    name: MindBalanceCluster.HealthBehaviors,
    language: Language.English,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'Your Health Behaviors score is in the average range in comparison to other youth athletes, which means you are likely doing some things that are important to physical health and mental health outside of sport, but have some areas to improve on. Youth athletes with high scores in this area feel a good balance between life and sport, limit their social media use, have good sleep habits, and eat well.',
  },
  {
    name: MindBalanceCluster.HealthBehaviors,
    language: Language.English,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'Your Health Behaviors score is in the above average range in comparison to other youth athletes, which means you are likely doing things that are important to physical health and mental health outside of sport. Youth athletes with high scores in this area feel a good balance between life and sport, limit social media use, have good sleep habits, and eat well.',
  },
  // Growth Mindset - Spanish
  {
    name: MindBalanceCluster.GrowthMindset,
    language: Language.Spanish,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'PLACEHOLDER - Por favor agregue contenido del PDF para Mentalidad de Crecimiento rango de percentil 10-20',
  },
  {
    name: MindBalanceCluster.GrowthMindset,
    language: Language.Spanish,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'PLACEHOLDER - Por favor agregue contenido del PDF para Mentalidad de Crecimiento rango de percentil 30-40',
  },
  {
    name: MindBalanceCluster.GrowthMindset,
    language: Language.Spanish,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'PLACEHOLDER - Por favor agregue contenido del PDF para Mentalidad de Crecimiento rango de percentil 50-60',
  },
  {
    name: MindBalanceCluster.GrowthMindset,
    language: Language.Spanish,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'PLACEHOLDER - Por favor agregue contenido del PDF para Mentalidad de Crecimiento rango de percentil 70-80',
  },
  {
    name: MindBalanceCluster.GrowthMindset,
    language: Language.Spanish,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'PLACEHOLDER - Por favor agregue contenido del PDF para Mentalidad de Crecimiento rango de percentil 90-100',
  },
  // Self-Confidence - Spanish
  {
    name: MindBalanceCluster.SelfConfidence,
    language: Language.Spanish,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'PLACEHOLDER - Por favor agregue contenido del PDF para Autoconfianza rango de percentil 10-20',
  },
  {
    name: MindBalanceCluster.SelfConfidence,
    language: Language.Spanish,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'PLACEHOLDER - Por favor agregue contenido del PDF para Autoconfianza rango de percentil 30-40',
  },
  {
    name: MindBalanceCluster.SelfConfidence,
    language: Language.Spanish,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'PLACEHOLDER - Por favor agregue contenido del PDF para Autoconfianza rango de percentil 50-60',
  },
  {
    name: MindBalanceCluster.SelfConfidence,
    language: Language.Spanish,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'PLACEHOLDER - Por favor agregue contenido del PDF para Autoconfianza rango de percentil 70-80',
  },
  {
    name: MindBalanceCluster.SelfConfidence,
    language: Language.Spanish,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'PLACEHOLDER - Por favor agregue contenido del PDF para Autoconfianza rango de percentil 90-100',
  },
  // Team Culture - Spanish
  {
    name: MindBalanceCluster.TeamCulture,
    language: Language.Spanish,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'PLACEHOLDER - Por favor agregue contenido del PDF para Cultura de Equipo rango de percentil 10-20',
  },
  {
    name: MindBalanceCluster.TeamCulture,
    language: Language.Spanish,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'PLACEHOLDER - Por favor agregue contenido del PDF para Cultura de Equipo rango de percentil 30-40',
  },
  {
    name: MindBalanceCluster.TeamCulture,
    language: Language.Spanish,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'PLACEHOLDER - Por favor agregue contenido del PDF para Cultura de Equipo rango de percentil 50-60',
  },
  {
    name: MindBalanceCluster.TeamCulture,
    language: Language.Spanish,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'PLACEHOLDER - Por favor agregue contenido del PDF para Cultura de Equipo rango de percentil 70-80',
  },
  {
    name: MindBalanceCluster.TeamCulture,
    language: Language.Spanish,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'PLACEHOLDER - Por favor agregue contenido del PDF para Cultura de Equipo rango de percentil 90-100',
  },
  // Health Behaviors - Spanish
  {
    name: MindBalanceCluster.HealthBehaviors,
    language: Language.Spanish,
    minPercentile: 10,
    maxPercentile: 20,
    meaning: 'PLACEHOLDER - Por favor agregue contenido del PDF para Comportamientos Saludables rango de percentil 10-20',
  },
  {
    name: MindBalanceCluster.HealthBehaviors,
    language: Language.Spanish,
    minPercentile: 30,
    maxPercentile: 40,
    meaning: 'PLACEHOLDER - Por favor agregue contenido del PDF para Comportamientos Saludables rango de percentil 30-40',
  },
  {
    name: MindBalanceCluster.HealthBehaviors,
    language: Language.Spanish,
    minPercentile: 50,
    maxPercentile: 60,
    meaning: 'PLACEHOLDER - Por favor agregue contenido del PDF para Comportamientos Saludables rango de percentil 50-60',
  },
  {
    name: MindBalanceCluster.HealthBehaviors,
    language: Language.Spanish,
    minPercentile: 70,
    maxPercentile: 80,
    meaning: 'PLACEHOLDER - Por favor agregue contenido del PDF para Comportamientos Saludables rango de percentil 70-80',
  },
  {
    name: MindBalanceCluster.HealthBehaviors,
    language: Language.Spanish,
    minPercentile: 90,
    maxPercentile: 100,
    meaning: 'PLACEHOLDER - Por favor agregue contenido del PDF para Comportamientos Saludables rango de percentil 90-100',
  },
];

