export const sampleData = {
    "result": {
        "responseId": "R_ujMsW9296ZXnEHv",
        "values": {
            "startDate": "2022-11-21T19:29:34Z",
            "endDate": "2022-11-21T19:30:51Z",
            "status": 1,
            "progress": 100,
            "duration": 76,
            "finished": 1,
            "recordedDate": "2022-11-21T19:30:53.788Z",
            "distributionChannel": "preview",
            "userLanguage": "EN",
            "QID9_TEXT": "McKenzie Test",
            "QID12_TEXT": "mbromback@premiersportpsychology.com",
            "QID13_TEXT": 27,
            "QID14": 2,
            "QID14_DO": [
                "1",
                "2",
                "3",
                "4"
            ],
            "QID16": [
                "1"
            ],
            "QID16_DO": [
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8"
            ],
            "QID58": [
                "14"
            ],
            "QID58_DO": [
                "1",
                "2",
                "30",
                "14",
                "27",
                "4",
                "12",
                "8",
                "10",
                "23",
                "31",
                "26",
                "11",
                "3",
                "7",
                "5",
                "13",
                "32",
                "29",
                "6",
                "9",
                "22"
            ],
            "QID54": 3,
            "QID54_DO": [
                "1",
                "3"
            ],
            "QID55": 5,
            "QID55_DO": [
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8"
            ],
            "QID18": 3,
            "QID18_DO": [
                "12",
                "7",
                "3",
                "2",
                "6",
                "10"
            ],
            "QID68": 1,
            "QID68_DO": [
                "1",
                "2",
                "3"
            ],
            "QID11": [
                "21"
            ],
            "QID11_DO": [
                "1",
                "2",
                "3",
                "11",
                "4",
                "5",
                "14",
                "15",
                "6",
                "8",
                "9",
                "13",
                "18",
                "19",
                "20",
                "21",
                "12"
            ],
            "QID69_41": 5,
            "QID69_42": 3,
            "QID69_43": 4,
            "QID69_44": 5,
            "QID69_45": 3,
            "QID69_46": 5,
            "QID69_47": 4,
            "QID69_48": 3,
            "QID69_49": 5,
            "QID69_50": 4,
            "QID69_51": 4,
            "QID69_52": 4,
            "QID69_53": 5,
            "QID69_DO": [
                "13",
                "9",
                "4",
                "1",
                "6",
                "12",
                "10",
                "11",
                "3",
                "7",
                "2",
                "5",
                "8"
            ],
            "QID1_29": 3,
            "QID1_30": 2,
            "QID1_31": 3,
            "QID1_32": 1,
            "QID1_33": 1,
            "QID1_34": 2,
            "QID1_35": 2,
            "QID1_36": 2,
            "QID1_37": 3,
            "QID1_38": 3,
            "QID1_39": 1,
            "QID1_40": 2,
            "QID1_46": 3,
            "QID1_DO": [
                "1",
                "9",
                "3",
                "10",
                "13",
                "2",
                "7",
                "12",
                "8",
                "6",
                "11",
                "5",
                "4"
            ],
            "QID70_3": 5,
            "QID70_4": 3,
            "QID70_17": 4,
            "QID70_18": 4,
            "QID70_19": 4,
            "QID70_20": 5,
            "QID70_21": 4,
            "QID70_22": 3,
            "QID70_23": 4,
            "QID70_24": 5,
            "QID70_25": 3,
            "QID70_26": 5,
            "QID70_28": 5,
            "QID70_DO": [
                "12",
                "13",
                "10",
                "1",
                "6",
                "3",
                "5",
                "7",
                "9",
                "4",
                "8",
                "2",
                "11"
            ],
            "SC_0vTuzWCZi3hYacS": 77,
            "SC_8kQ8OHepQQdjW86": 76,
            "SC_b4sOCUsBpe4w1wi": 40,
            "SC_bEeQPzB6jZL5Rm6": 34,
            "SC_egqBzHR6cAQfDOm": 28,
            "Q_Language": "EN",
            "Level": "Collegiate",
            "TotalScore": "6.67",
            "GrowthScore": "5.92",
            "GrowthPercentile": "Your score falls within the 30th percentile when compared to other athletes at your level. That means that 30% of athletes at your level have received your score or below and 70% of athletes at your level hold scores higher than yours in growth mindset.",
            "GP": "30th",
            "Growth Mindset Message": "Your Growth Mindset score is in the below average range compared to other college athletes, which suggests you may be quite hard on yourself as an athlete. Athletes with scores similar to you are likely to seek perfection in sport and become hooked by negative thoughts and feelings that arise while training and competing. You may also set high expectations for yourself and feel pressure around your success within performance. Perhaps you even feel as though your worth is directly affected by the outcome of your performance or ability. Although this can be motivating, too much rigidity around these expectations can lead to self-judgement and feelings of anxiousness around making mistakes. To improve your scores in this area, try practicing flexibility and understanding around mistakes through monitoring your self-talk. For example, acknowledge the moments that are imperfect and try to reframe these imperfections as learning opportunities to search for ways of growth. It can be difficult to challenge these thoughts, but by first becoming more aware of your inner dialog, you can start to deconstruct your inner critiques and rebuild an inner dialogue that is more understanding and compassionate towards yourself.",
            "Growth Mindset Spanish": "Obtuvo una puntuación en mentalidad de crecimiento, que se encuentra por debajo del promedio en comparación con otros atletas.\n\nSu puntaje de mentalidad de crecimiento sugiere que puede ser bastante duro consigo mismo(a) como atleta. Es posible que busque la perfección en el deporte y tenga dificultades para deshacerse de los pensamientos y sentimientos negativos que surgen mientras entrena y compite.\n\nLos atletas con puntajes como los suyos establecen altas expectativas y suelen sentirse agobiados(as)  por el estrés de cumplir con esas expectativas y lograr el éxito. Quizás incluso sienta que su valor se ve afectado directamente por el resultado de su desempeño o habilidad. Si bien esto puede ser motivador, demasiada rigidez en torno a estas expectativas puede conducir a la autocrítica y la ansiedad por cometer errores.\n\nPara mejorar su mentalidad de crecimiento, intente practicar la flexibilidad y la comprensión de errores mediante el control de su diálogo interno. Por ejemplo, reconozca los momentos que son imperfectos y trate de replantear estas imperfecciones como oportunidades de aprendizaje para buscar formas de crecimiento. Puede ser difícil desafiar estos pensamientos, pero si primero uno es consciente de su diálogo interno, uno puede comenzar a deconstruir sus críticas internas y reconstruir un diálogo interno que sea más comprensivo y compasivo consigo mismo.",
            "Performance": "6.91",
            "PerformancePercentile": "Your score falls within the 40th percentile when compared to other athletes at your level. This means that 40% of athletes at your level have received your score or below and 60% of athletes at your level hold scores higher than yours in performance mindset.",
            "PP": "40th",
            "Performance Mindset Message": "Your Performance Mindset score is in the average range when compared to other college athletes, which means you may be proficient in some aspects of the mental side of sports, but may struggle with consistency. People who score highly in this category tend to proactively work to set clear, meaningful goals related to the process rather than the outcome. They prepare themselves mentally before competitions through aspects such as mindfulness, imagery, and present-moment focus.  To improve your performance mindset, consider regularly engaging in a pre-performance routine, mindfulness activities, and goal setting activities for your upcoming season.",
            "Performance Mindset Message Spanish": "Obtuvo una puntuación en Mentalidad de rendimiento, que se encuentra dentro del promedio en comparación con otros atletas.\n\nSu puntaje de mentalidad de rendimiento sugiere que puede ser competente en algunos aspectos del lado mental de los deportes, pero no mantener esa mentalidad de manera constante.\nLos atletas con puntajes similares a los suyos tienden a reconocer algunos aspectos de la preparación mental antes de las competencias, y utilizan la atención plena, la visualización y el enfoque al momento presente, pero de manera inconsistente.\n\nPara aumentar aún más su mentalidad de rendimiento, trabaje en establecer de manera proactiva objetivos claros y significativos relacionados con el proceso en lugar del resultado. Considere crear una rutina previa a la actuación, participar en actividades de atención plena y crear algunas metas para su próxima temporada.",
            "Team": "8",
            "TeamPercentile": "Your score falls within the 50th percentile when compared to other athletes at your level. That means that 50% of athletes at your level have received your score or below and 50% of athletes at your level hold scores higher than yours in team support.",
            "TP": "50th",
            "Team Support Message": "Your Team Support score is in the average range in comparison to other college athletes, which means you may feel supported occasionally, but there may be moments where you feel disconnected with your team or coach(es). It may be that you feel support from your team, but not your coach(es) or vice versa. There is also a chance that you feel supported by your team and coach(es) but it depends on how you perform. To improve your score in this area, reflect on who you feel supported by in your sport, when you feel the most supported, and moments you feel like your needs were met once you spoke up. Once you have reflected on these things, notice the times you felt as though you were cared about as an athlete and as an individual beyond sport. This can help you become aware of opportunities to connect with others outside of training or competition on a more personal level. Implement what you reflected on by noticing moments where you may distance yourself from others versus opening up to others.",
            "Team Support Message Spanish": "Obtuvo una puntuación en Apoyo en equipo, que se encuentra dentro del promedio en comparación con otros atletas.\n\nEl puntaje de Apoyo de Equipo sugiere que puede sentirse apoyado(a) ocasionalmente, pero puede haber momentos en los que se sienta desconectado(a) de su equipo o entrenador(a).\n\nLos atletas con puntajes como los suyos tienden a sentir el apoyo de su equipo, pero no de su entrenador(a) o viceversa. En ocasiones, puede estar determinado por el rendimiento.\n\nPara continuar creciendo en el apoyo del equipo, reflexione sobre ¿Quién lo apoya en su deporte?, ¿Cuándo se siente  más apoyado(a)? y los momentos en los que sintió  que sus necesidades se cumplieron una vez que habló. Una vez que haya reflexionado sobre estos aspectos, observe las veces que sintió que lo cuidaban como atleta y como individuo más allá del deporte. Esto puede ayudarlo a conocer las oportunidades para conectarse con otros fuera del entrenamiento o la competencia a un nivel más personal. Implemente lo que reflexionó al darse cuenta de los momentos en los que puede distanciarse en lugar de abrirse a los demás.",
            "Physical": "6.8",
            "PhysicalPercentile": "Your score falls within the 30th percentile when compared to other athletes at your level. That means that 30% of athletes at your level have received your score or below and 70% of athletes at your level hold scores higher than yours in physical wellness.",
            "PhP": "30th",
            "Physical Wellness Message": "Your Physical Wellness score is in the below average range in comparison to other collegiate athletes, which suggests you may be struggling to prioritize sleep or physical wellness in recent weeks. Athletes with low scores in this area are likely to have inconsistent sleep habits and may not receive the amount of sleep needed to promote health and recovery. They may not be as intentional with nutrition and hydration as they could be, which could lead to difficulties with health or performance. Athletes with low scores in this area are also likely to ignore important warning signs regarding injuries, plateaus, or burnout. To improve your scores in this area, start by improving sleep patterns and habits so you get enough high quality sleep. Consider whether your current hydration and nutrition regimen supports your wellness and performance goals. Prioritize the recovery process by minimizing physical and mental stress on your recovery days. Finally, be sure to communicate any concerns with coaching staff in order to prevent injuries, plateaus, or burnout.",
            "Physical Wellness Message Spanish": "Obtuvo una puntuación en Bienestar físico, que se encuentra por debajo del promedio en comparación con otros atletas.\n\nSu puntaje de Bienestar Físico sugiere que puede estar luchando para priorizar el sueño o el bienestar físico en las últimas semanas. \n\nEs probable que los atletas con puntajes como el suyo tengan hábitos de sueño inconsistentes y no reciban la cantidad necesaria para promover la salud y la recuperación. Es posible que no sea tan intencional con la nutrición y la hidratación como podría ser, lo que podría ocasionar dificultades con la salud o el rendimiento. También puede estar ignorando las señales de advertencia importantes con respecto a lesiones, o agotamiento.\n\nPara aumentar su bienestar físico, comience por mejorar los patrones y hábitos de sueño para que pueda dormir lo suficiente de alta calidad. Considere si su régimen actual de hidratación y nutrición respalda sus objetivos de bienestar y rendimiento. Priorice el proceso de recuperación minimizando el estrés físico y mental en sus días de recuperación. Por último, asegúrese de comunicar cualquier inquietud al personal técnico para evitar lesiones, estancamiento o agotamiento.",
            "Mental": "5.6",
            "MentalPercentile": "Your score falls within the 30th percentile when compared to other athletes at your level. That means that 30% of athletes at your level have received your score or below and 70% of athletes at your level hold scores higher than yours in mental wellness.",
            "MP": "30th",
            "Mental Wellness Message": "Your Mental Wellness score is in the below average range in comparison to other collegiate athletes, which suggests you may not be actively using counseling or other sport psychology resources for athletes like yourself. Athletes with low scores in this area are not likely to reflect on how their personal circumstances, backgrounds, or cultural identities contribute to their role in sport. However, taking time to self-reflect is crucial to growth! To improve your scores in this area, speak with your coach or a team member to learn about the resources that are available to you. Consider whether there are barriers to seeking care when needed, such as stigma or a lack of information about resources. Additionally, take some time to reflect on how your identities and experiences affect your wellness in and outside of sport.",
            "Mental Wellness Message Spanish": "Obtuvo una puntuación en Bienestar mental, que se encuentra  por debajo del promedio en comparación con otros atletas.\n\nSu puntaje de Bienestar Mental sugiere que es posible que no esté utilizando activamente el asesoramiento u otros recursos de psicología deportiva para atletas como usted.\n\nEs poco probable que los atletas con puntajes como los suyos reflexionen sobre cómo sus circunstancias personales, antecedentes o identidades culturales contribuyen a su papel en el deporte. Asegúrese de tomarse el tiempo para reflexionar sobre sí mismo(a), ya que es crucial para el crecimiento.\n\nPara mejorar su bienestar mental, hable con su entrenador(a) o un miembro del equipo para conocer los recursos que están disponibles para usted. Considere si existen barreras para buscar atención cuando sea necesario, como el estigma o la falta de información sobre los recursos. Además, tómese un tiempo para reflexionar sobre cómo sus identidades y experiencias afectan su bienestar dentro y fuera del deporte."
        },
        "labels": {
            "status": "Survey Preview",
            "finished": "True",
            "QID14": "Woman",
            "QID14_DO": [
                "Man",
                "Woman",
                "Non-binary",
                "Not listed above (specify below)"
            ],
            "QID16": [
                "White"
            ],
            "QID16_DO": [
                "White",
                "Black or African American",
                "American Indian or Alaska Native",
                "Asian",
                "Native Hawaiian or Pacific Islander",
                "MENA (Middle Eastern/North African)",
                "Latino/Latina/Latinx",
                "Not mentioned above (specify below)"
            ],
            "QID58": [
                "Curling"
            ],
            "QID58_DO": [
                "Basketball",
                "Baseball",
                "Boxing",
                "Curling",
                "Cycling",
                "Football",
                "Golf",
                "Gymnastics",
                "Hockey",
                "Lacrosse",
                "Mixed Martial Arts",
                "Rowing",
                "Soccer",
                "Softball",
                "Swimming",
                "Tennis",
                "Track & Field/Cross Country",
                "Triathlon",
                "Weight Lifting",
                "Wrestling",
                "Volleyball",
                "Not mentioned above (specify below)"
            ],
            "QID54": "In competition season (actively competing or performing)",
            "QID54_DO": [
                "Off season (not actively engaging in formal training or preparing for competitions) or Pre-season (training regularly to prepare for competition season)",
                "In competition season (actively competing or performing)"
            ],
            "QID55": "4",
            "QID55_DO": [
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7"
            ],
            "QID18": "Collegiate",
            "QID18_DO": [
                "Olympic and/or National team",
                "Professional",
                "Collegiate",
                "High School or Youth Recreational/Club",
                "Semi-Professional or Adult Amateur",
                "Adult Recreational (18 and older)"
            ],
            "QID68": "Division I",
            "QID68_DO": [
                "Division I",
                "Division II",
                "Division III"
            ],
            "QID11": [
                "McKenzie Bromback"
            ],
            "QID11_DO": [
                "Dr. Justin Anderson",
                "Dr. Carly Anderson",
                "Dr. Erin Ayala",
                "Carlos Coto",
                "Dr. Adam Gallenberg",
                "Dr. Ben Merkling",
                "Dr. Matthew Mikesell",
                "Nate Penz",
                "Dr. Jaimie Rubin",
                "Dr. Ashley Zapata",
                "Alexandra Wulbecker-Smith",
                "Dr. Chrissy Holm Haider",
                "Dr. Janet Finlayson",
                "Dr. Kirbi Kidd",
                "Dr. Phil Imholte",
                "McKenzie Bromback",
                "Not Applicable"
            ],
            "QID69_41": "Always",
            "QID69_42": "Sometimes",
            "QID69_43": "Often",
            "QID69_44": "Always",
            "QID69_45": "Sometimes",
            "QID69_46": "Always",
            "QID69_47": "Often",
            "QID69_48": "Sometimes",
            "QID69_49": "Always",
            "QID69_50": "Often",
            "QID69_51": "Often",
            "QID69_52": "Often",
            "QID69_53": "Always",
            "QID69_DO": [
                "I felt like my teammates care about my wellbeing",
                "I effectively managed performance related anxiety",
                "I had measurable short-term goals that focus on the process",
                "I talked to my coach(es) about what is going well and what isn't",
                "I fueled my body with the nutrients needed to promote health and recovery",
                "I set goals that are personally meaningful",
                "I felt like I have a voice on my team",
                "I was afraid of failure",
                "I felt valued by coaches and teammates regardless of my performance",
                "I was able to separate my self worth from the outcome of practice or competitions",
                "I got the amount of sleep needed to promote health and recovery",
                "I was able to let go of mistakes I make as an athlete",
                "I practiced good sleep habits to get high quality sleep (e.g., limit screen time, consistent bedtime)"
            ],
            "QID1_29": "Sometimes",
            "QID1_30": "Rarely",
            "QID1_31": "Sometimes",
            "QID1_32": "Never",
            "QID1_33": "Never",
            "QID1_34": "Rarely",
            "QID1_35": "Rarely",
            "QID1_36": "Rarely",
            "QID1_37": "Sometimes",
            "QID1_38": "Sometimes",
            "QID1_39": "Never",
            "QID1_40": "Rarely",
            "QID1_46": "Sometimes",
            "QID1_DO": [
                "I engaged in honest self-reflection to continuously discover the best version of myself",
                "I was able to let go of unhelpful or negative thoughts, rather than getting caught up in them",
                "I viewed each experience in training and competition as something I can reflect on and learn from",
                "I used resources around me such as counseling, sport psychology, or support groups",
                "I was able to shift my mindset when things weren't going well",
                "I was nice to myself when I needed to take a break",
                "I focused on the things I could control",
                "I felt like I had meaningful relationships with teammates",
                "I set aside time for mental preparation before competitions",
                "I used strategies to increase my motivation when needed",
                "I was willing to get professional mental health support if needed, regardless of what others may think",
                "I practiced being in the present moment when competing and training",
                "I followed guidelines to prevent injury, plateaus, or burnout"
            ],
            "QID70_3": "Always",
            "QID70_4": "Sometimes",
            "QID70_17": "Often",
            "QID70_18": "Often",
            "QID70_19": "Often",
            "QID70_20": "Always",
            "QID70_21": "Often",
            "QID70_22": "Sometimes",
            "QID70_23": "Often",
            "QID70_24": "Always",
            "QID70_25": "Sometimes",
            "QID70_26": "Always",
            "QID70_28": "Always",
            "QID70_DO": [
                "I mentally prepared myself for adversity",
                "I expected perfection in life and sport",
                "I took care of my physical wellbeing during intense training periods",
                "I believed in myself",
                "I thought about the \"why\" behind what I do",
                "I took care of my mental health during intense training periods",
                "I embraced opportunities to step outside of my comfort zone",
                "I understood how past difficult or traumatic experiences affect me today",
                "I observed and accepted emotions, rather than allowing them to take over my experience",
                "I used refocusing techniques when training or performing to focus on what was important in the moment",
                "I talked openly and honestly with others about my mental and physical health",
                "I reflected on incidents of prejudice, discrimination, or bias that took place in sport",
                "I was kind to myself when I didn’t meet my expectations"
            ]
        },
        "displayedFields": [
            "QID69_42_SC_bEeQPzB6jZL5Rm6",
            "QID1_46_SC_0vTuzWCZi3hYacS",
            "QID1_29",
            "QID70_24_SC_bEeQPzB6jZL5Rm6",
            "QID70_3_SC_0vTuzWCZi3hYacS",
            "QID70_4_SC_egqBzHR6cAQfDOm",
            "QID66_TEXT",
            "QID69_52_SC_8kQ8OHepQQdjW86",
            "QID12_TEXT",
            "QID69_46_SC_bEeQPzB6jZL5Rm6",
            "QID70_28_SC_0vTuzWCZi3hYacS",
            "QID1_39_SC_egqBzHR6cAQfDOm",
            "QID69_44_SC_8kQ8OHepQQdjW86",
            "QID1_30",
            "QID58_22_TEXT",
            "QID1_31",
            "QID1_32",
            "QID14_4_TEXT",
            "QID1_33",
            "QID1_34",
            "QID1_35",
            "QID1_29_SC_8kQ8OHepQQdjW86",
            "QID69_50_SC_b4sOCUsBpe4w1wi",
            "QID1_36",
            "QID1_37",
            "QID69_53_SC_b4sOCUsBpe4w1wi",
            "QID1_38",
            "QID1_39",
            "QID70_21_SC_egqBzHR6cAQfDOm",
            "QID70_18_SC_8kQ8OHepQQdjW86",
            "QID70_22_SC_egqBzHR6cAQfDOm",
            "QID1_34_SC_8kQ8OHepQQdjW86",
            "QID1_33_SC_8kQ8OHepQQdjW86",
            "QID70_18",
            "QID70_17",
            "QID1_31_SC_8kQ8OHepQQdjW86",
            "QID70_19",
            "QID70_25",
            "QID70_24",
            "QID70_26",
            "QID70_21",
            "QID1_36_SC_8kQ8OHepQQdjW86",
            "QID70_20",
            "QID69_43_SC_b4sOCUsBpe4w1wi",
            "QID9_TEXT",
            "QID70_23",
            "QID1_40",
            "QID70_22",
            "QID70_4",
            "QID70_20_SC_8kQ8OHepQQdjW86",
            "QID69_41_SC_b4sOCUsBpe4w1wi",
            "QID70_3",
            "QID1_46",
            "QID70_26_SC_8kQ8OHepQQdjW86",
            "QID69_49_SC_0vTuzWCZi3hYacS",
            "QID18",
            "QID16",
            "QID69_47_SC_0vTuzWCZi3hYacS",
            "QID69_43",
            "QID69_42",
            "QID70_28",
            "QID70_25_SC_0vTuzWCZi3hYacS",
            "QID69_41",
            "QID69_47",
            "QID69_46",
            "QID69_45",
            "QID69_44",
            "QID69_45_SC_0vTuzWCZi3hYacS",
            "QID69_49",
            "QID69_48",
            "QID70_19_SC_8kQ8OHepQQdjW86",
            "QID58",
            "QID14",
            "QID55",
            "QID11",
            "QID54",
            "QID1_38_SC_egqBzHR6cAQfDOm",
            "QID72_TEXT",
            "QID70_17_SC_0vTuzWCZi3hYacS",
            "QID69_50",
            "QID16_8_TEXT",
            "QID70_23_SC_0vTuzWCZi3hYacS",
            "QID69_53",
            "QID69_52",
            "QID69_51",
            "QID1_32_SC_bEeQPzB6jZL5Rm6",
            "QID69_48_SC_bEeQPzB6jZL5Rm6",
            "QID1_40_SC_b4sOCUsBpe4w1wi",
            "QID13_TEXT",
            "QID1_37_SC_0vTuzWCZi3hYacS",
            "QID68",
            "QID1_35_SC_0vTuzWCZi3hYacS",
            "QID1_30_SC_0vTuzWCZi3hYacS",
            "QID69_51_SC_0vTuzWCZi3hYacS"
        ],
        "displayedValues": {
            "QID1_29": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID1_30": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID1_31": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID1_32": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID1_33": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID1_34": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID1_35": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID1_36": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID1_37": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID1_38": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID1_39": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID70_18": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID70_17": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID70_19": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID70_25": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID70_24": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID70_26": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID70_21": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID70_20": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID70_23": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID1_40": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID70_22": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID70_4": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID70_3": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID1_46": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID18": [
                12,
                7,
                3,
                2,
                6,
                10
            ],
            "QID16": [
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8"
            ],
            "QID69_43": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID69_42": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID70_28": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID69_41": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID69_47": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID69_46": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID69_45": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID69_44": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID69_49": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID69_48": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID58": [
                "1",
                "2",
                "30",
                "14",
                "27",
                "4",
                "12",
                "8",
                "10",
                "23",
                "31",
                "26",
                "11",
                "3",
                "7",
                "5",
                "13",
                "32",
                "29",
                "6",
                "9",
                "22"
            ],
            "QID14": [
                1,
                2,
                3,
                4
            ],
            "QID55": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8
            ],
            "QID11": [
                "1",
                "2",
                "3",
                "11",
                "4",
                "5",
                "14",
                "15",
                "6",
                "8",
                "9",
                "13",
                "18",
                "19",
                "20",
                "21",
                "12"
            ],
            "QID54": [
                1,
                3
            ],
            "QID69_50": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID69_53": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID69_52": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID69_51": [
                1,
                2,
                3,
                4,
                5
            ],
            "QID68": [
                1,
                2,
                3
            ]
        }
    },
    "meta": {
        "requestId": "c9b0e181-29a3-4ed0-b563-4df92dd29794",
        "httpStatus": "200 - OK",
        "notice": "Request proxied. For faster response times, use this host instead: iad1.qualtrics.com"
    }
}